// Lote 3 de Química Geral — Tópico 3: Termodinâmica, Cinética e Equilíbrio.
// Estilo Brown, "Química: A Ciência Central" (caps. 5, 14, 15, 16, 17, 19 e 20):
// termoquímica, entropia e energia livre, cinética, equilíbrio químico e iônico
// e eletroquímica. Sem questões `facil`.
const R = String.raw;
const T = "Termodinâmica, Cinética e Equilíbrio";

export const questoes = [
  {
    topico: T,
    subtopico: "Calorimetria e calor específico",
    dificuldade: "dificil",
    enunciado: R`Um bloco metálico de $100{,}0$ g a $80{,}0\ ^{\circ}\text{C}$ é mergulhado em $100{,}0$ g de água a $20{,}0\ ^{\circ}\text{C}$, num calorímetro de capacidade desprezível. O equilíbrio térmico ocorre a $25{,}0\ ^{\circ}\text{C}$. Determine o calor específico do metal, usando $c_{\text{água}}=4{,}18$ J/(g·°C).`,
    correta: R`$0{,}38$ J/(g·°C)`,
    distratores: [
      R`$0{,}76$ J/(g·°C)`,
      R`$0{,}19$ J/(g·°C)`,
      R`$4{,}18$ J/(g·°C)`,
      R`$0{,}45$ J/(g·°C)`,
    ],
    resolucao: R`O calor cedido pelo metal é absorvido pela água: $m_mc_m\Delta T_m=m_ac_a\Delta T_a$. A água aquece $5{,}0\ ^{\circ}\text{C}$ e absorve $100{,}0\times 4{,}18\times 5{,}0=2090$ J. O metal esfria de $80{,}0$ para $25{,}0\ ^{\circ}\text{C}$, isto é, $55{,}0\ ^{\circ}\text{C}$. Logo $c_m=\dfrac{2090}{100{,}0\times 55{,}0}=0{,}38$ J/(g·°C). O valor é típico de metais como o cobre e ilustra por que massas iguais de metal e água trocam calor com variações de temperatura tão diferentes.`,
  },
  {
    topico: T,
    subtopico: "Calorímetro de bomba a volume constante",
    dificuldade: "dificil",
    enunciado: R`A combustão de $1{,}50$ g de glicose ($M=180$ g/mol) numa bomba calorimétrica de capacidade $5{,}00$ kJ/°C provoca elevação de $4{,}67\ ^{\circ}\text{C}$ na temperatura. Determine a variação de energia interna da combustão, por mol de glicose.`,
    correta: R`$-2{,}80\times 10^{3}$ kJ/mol`,
    distratores: [
      R`$-1{,}40\times 10^{3}$ kJ/mol`,
      R`$-5{,}60\times 10^{3}$ kJ/mol`,
      R`$-2{,}34\times 10^{1}$ kJ/mol`,
      R`$-4{,}67\times 10^{2}$ kJ/mol`,
    ],
    resolucao: R`O calor absorvido pelo calorímetro é $q=C\,\Delta T=5{,}00\times 4{,}67=23{,}4$ kJ, liberado pela amostra. A quantidade queimada é $n=\dfrac{1{,}50}{180}=8{,}33\times 10^{-3}$ mol. Por mol, $\Delta E=-\dfrac{23{,}4}{8{,}33\times 10^{-3}}\approx-2{,}80\times 10^{3}$ kJ/mol. Como a bomba opera a volume constante, o calor medido é $\Delta E$, e não $\Delta H$ — para a glicose os dois praticamente coincidem, porque a reação não altera o número de mols de gás.`,
  },
  {
    topico: T,
    subtopico: "Lei de Hess",
    dificuldade: "dificil",
    enunciado: R`São dados $\text{C}(s)+\text{O}_2(g)\rightarrow\text{CO}_2(g)$, com $\Delta H=-393{,}5$ kJ, e $\text{CO}(g)+\tfrac12\text{O}_2(g)\rightarrow\text{CO}_2(g)$, com $\Delta H=-283{,}0$ kJ. Determine $\Delta H$ da reação $\text{C}(s)+\tfrac12\text{O}_2(g)\rightarrow\text{CO}(g)$.`,
    correta: R`$-110{,}5$ kJ`,
    distratores: [R`$-676{,}5$ kJ`, R`$+110{,}5$ kJ`, R`$-283{,}0$ kJ`, R`$-393{,}5$ kJ`],
    resolucao: R`Some a primeira equação com o inverso da segunda. Ao inverter, o sinal muda: $\text{CO}_2(g)\rightarrow\text{CO}(g)+\tfrac12\text{O}_2(g)$, com $\Delta H=+283{,}0$ kJ. O $\text{CO}_2$ aparece dos dois lados e é cancelado, sobrando exatamente a equação pedida, com $\Delta H=-393{,}5+283{,}0=-110{,}5$ kJ. Essa medida indireta é necessária porque a combustão do carbono nunca produz apenas $\text{CO}$ — a lei de Hess contorna a impossibilidade experimental.`,
  },
  {
    topico: T,
    subtopico: "Entalpia de formação a partir da combustão",
    dificuldade: "dificil",
    enunciado: R`A combustão completa do etanol líquido libera $1367$ kJ/mol. Sabendo que $\Delta H_f^{\circ}$ vale $-393{,}5$ kJ/mol para o $\text{CO}_2(g)$ e $-285{,}8$ kJ/mol para a $\text{H}_2\text{O}(l)$, determine a entalpia de formação do etanol.`,
    correta: R`$-277{,}4$ kJ/mol`,
    distratores: [
      R`$-1367{,}0$ kJ/mol`,
      R`$+277{,}4$ kJ/mol`,
      R`$-1644{,}4$ kJ/mol`,
      R`$-138{,}7$ kJ/mol`,
    ],
    resolucao: R`A reação é $\text{C}_2\text{H}_5\text{OH}(l)+3\text{O}_2(g)\rightarrow 2\text{CO}_2(g)+3\text{H}_2\text{O}(l)$, e vale $\Delta H^{\circ}=\sum\Delta H_f^{\circ}(\text{produtos})-\sum\Delta H_f^{\circ}(\text{reagentes})$. Os produtos somam $2(-393{,}5)+3(-285{,}8)=-1644{,}4$ kJ; o oxigênio, substância simples, tem entalpia de formação nula. Assim $-1367=-1644{,}4-\Delta H_f^{\circ}(\text{etanol})$, de onde $\Delta H_f^{\circ}=-277{,}4$ kJ/mol.`,
  },
  {
    topico: T,
    subtopico: "Relação entre entalpia e energia interna",
    dificuldade: "dificil",
    enunciado: R`Para $\text{N}_2(g)+3\text{H}_2(g)\rightarrow 2\text{NH}_3(g)$ tem-se $\Delta H^{\circ}=-92{,}2$ kJ a $298$ K. Determine $\Delta E^{\circ}$, usando $R=8{,}314\times 10^{-3}$ kJ/(mol·K).`,
    correta: R`$-87{,}2$ kJ`,
    distratores: [R`$-97{,}2$ kJ`, R`$-92{,}2$ kJ`, R`$-82{,}3$ kJ`, R`$-102{,}1$ kJ`],
    resolucao: R`Vale $\Delta H=\Delta E+\Delta n_{\text{gás}}RT$. Aqui $\Delta n_{\text{gás}}=2-(1+3)=-2$, logo $\Delta n RT=-2\times 8{,}314\times 10^{-3}\times 298=-4{,}96$ kJ. Isolando, $\Delta E=\Delta H-\Delta nRT=-92{,}2+4{,}96=-87{,}2$ kJ. A contração do volume faz a vizinhança realizar trabalho sobre o sistema, e por isso a energia interna cai menos que a entalpia. O erro de sinal mais comum leva a $-97{,}2$ kJ.`,
  },
  {
    topico: T,
    subtopico: "Trabalho de expansão contra pressão constante",
    dificuldade: "dificil",
    enunciado: R`Um gás se expande de $2{,}0$ L para $6{,}0$ L contra uma pressão externa constante de $1{,}5$ atm. Determine o trabalho realizado sobre o gás, sabendo que $1$ L·atm $=101{,}3$ J.`,
    correta: R`$-6{,}1\times 10^{2}$ J`,
    distratores: [
      R`$+6{,}1\times 10^{2}$ J`,
      R`$-9{,}1\times 10^{2}$ J`,
      R`$-1{,}2\times 10^{3}$ J`,
      R`$-4{,}1\times 10^{2}$ J`,
    ],
    resolucao: R`Para pressão externa constante, $w=-P_{\text{ext}}\Delta V=-1{,}5\times(6{,}0-2{,}0)=-6{,}0$ L·atm. Convertendo, $-6{,}0\times 101{,}3\approx-6{,}1\times 10^{2}$ J. O sinal negativo segue a convenção de que $w$ é o trabalho recebido pelo sistema: numa expansão o gás empurra a vizinhança e perde energia. Repare que o trabalho depende da pressão de oposição, e não da pressão do gás — por isso uma expansão no vácuo não realiza trabalho algum.`,
  },
  {
    topico: T,
    subtopico: "Previsão do sinal da variação de entropia",
    dificuldade: "medio",
    enunciado: R`Em qual das transformações abaixo a variação de entropia do sistema é negativa?`,
    correta: R`$2\text{NO}(g)+\text{O}_2(g)\rightarrow 2\text{NO}_2(g)$`,
    distratores: [
      R`$\text{CaCO}_3(s)\rightarrow\text{CaO}(s)+\text{CO}_2(g)$`,
      R`$\text{H}_2\text{O}(l)\rightarrow\text{H}_2\text{O}(g)$`,
      R`$\text{NaCl}(s)\rightarrow\text{Na}^{+}(aq)+\text{Cl}^{-}(aq)$`,
      R`$2\text{H}_2\text{O}_2(l)\rightarrow 2\text{H}_2\text{O}(l)+\text{O}_2(g)$`,
    ],
    resolucao: R`O critério dominante é a variação do número de mols de gás, porque o estado gasoso tem entropia molar muito superior à dos condensados. Na reação escolhida, três mols de gás transformam-se em dois: o número de microestados acessíveis diminui e $\Delta S<0$. Nas demais há produção de gás ou passagem a um estado mais desordenado. Note que $\Delta S<0$ não impede a espontaneidade — a formação do $\text{NO}_2$ é espontânea porque é suficientemente exotérmica.`,
  },
  {
    topico: T,
    subtopico: "Cálculo de entropia padrão de reação",
    dificuldade: "dificil",
    enunciado: R`Calcule $\Delta S^{\circ}$ da reação $\text{N}_2(g)+3\text{H}_2(g)\rightarrow 2\text{NH}_3(g)$, usando as entropias padrão, em J/(mol·K): $\text{N}_2=191{,}5$; $\text{H}_2=130{,}6$; $\text{NH}_3=192{,}5$.`,
    correta: R`$-198{,}3$ J/K`,
    distratores: [R`$-129{,}8$ J/K`, R`$+198{,}3$ J/K`, R`$-390{,}8$ J/K`, R`$-99{,}2$ J/K`],
    resolucao: R`Aplique $\Delta S^{\circ}=\sum n S^{\circ}(\text{produtos})-\sum n S^{\circ}(\text{reagentes})$, sem esquecer os coeficientes. Produtos: $2\times 192{,}5=385{,}0$ J/K. Reagentes: $191{,}5+3\times 130{,}6=191{,}5+391{,}8=583{,}3$ J/K. Logo $\Delta S^{\circ}=385{,}0-583{,}3=-198{,}3$ J/K. O sinal negativo era previsível: quatro mols de gás condensam-se em dois, com forte perda de liberdade translacional.`,
  },
  {
    topico: T,
    subtopico: "Temperatura de inversão da espontaneidade",
    dificuldade: "dificil",
    enunciado: R`A decomposição $\text{CaCO}_3(s)\rightarrow\text{CaO}(s)+\text{CO}_2(g)$ tem $\Delta H^{\circ}=+178$ kJ/mol e $\Delta S^{\circ}=+160$ J/(mol·K). Determine a temperatura acima da qual o processo se torna espontâneo em condições padrão.`,
    correta: R`$1113$ K`,
    distratores: [R`$890$ K`, R`$1450$ K`, R`$835$ K`, R`$298$ K`],
    resolucao: R`A espontaneidade exige $\Delta G^{\circ}=\Delta H^{\circ}-T\Delta S^{\circ}<0$. Como ambos os termos são positivos, o produto $T\Delta S^{\circ}$ só supera $\Delta H^{\circ}$ acima de $T=\dfrac{\Delta H^{\circ}}{\Delta S^{\circ}}$. Cuidando das unidades, $T=\dfrac{178\,000}{160}\approx 1113$ K, cerca de $840\ ^{\circ}\text{C}$. É exatamente por isso que a calcinação industrial do calcário em fornos de cal opera em torno de $900\ ^{\circ}\text{C}$.`,
  },
  {
    topico: T,
    subtopico: "Relação entre energia livre padrão e constante de equilíbrio",
    dificuldade: "dificil",
    enunciado: R`Uma reação apresenta $\Delta G^{\circ}=-34{,}2$ kJ/mol a $298$ K. Determine sua constante de equilíbrio, usando $\Delta G^{\circ}=-RT\ln K$ e $R=8{,}314$ J/(mol·K).`,
    correta: R`$1{,}0\times 10^{6}$`,
    distratores: [
      R`$1{,}0\times 10^{-6}$`,
      R`$3{,}4\times 10^{4}$`,
      R`$1{,}4\times 10^{1}$`,
      R`$1{,}0\times 10^{3}$`,
    ],
    resolucao: R`Isolando, $\ln K=-\dfrac{\Delta G^{\circ}}{RT}=\dfrac{34\,200}{8{,}314\times 298}=\dfrac{34\,200}{2477{,}6}=13{,}8$. Logo $K=e^{13{,}8}\approx 1{,}0\times 10^{6}$. O resultado mostra a sensibilidade extrema de $K$ à energia livre: cada $5{,}7$ kJ/mol de $\Delta G^{\circ}$ multiplica ou divide $K$ por dez à temperatura ambiente. Sinal negativo de $\Delta G^{\circ}$ corresponde sempre a $K>1$, isto é, equilíbrio deslocado para os produtos.`,
  },
  {
    topico: T,
    subtopico: "Energia livre em condições não padrão",
    dificuldade: "dificil",
    enunciado: R`Para um sistema químico que atingiu o equilíbrio a temperatura e pressão constantes, é correto afirmar que:`,
    correta: R`$\Delta G=0$ e $\Delta G^{\circ}=-RT\ln K$`,
    distratores: [
      R`$\Delta G=\Delta G^{\circ}=0$ sempre`,
      R`$\Delta G^{\circ}=0$ e $\Delta G=-RT\ln Q$`,
      R`$\Delta G<0$ e $Q>K$ no equilíbrio`,
      R`$\Delta G>0$ e $Q=K$ fora do equilíbrio`,
    ],
    resolucao: R`No equilíbrio a energia livre do sistema está no mínimo, e qualquer avanço infinitesimal da reação não altera $G$: por isso $\Delta G=0$. Já $\Delta G^{\circ}$ compara reagentes e produtos todos no estado padrão, condição que em geral não é a do equilíbrio; ele é uma constante da reação, ligada a $K$ por $\Delta G^{\circ}=-RT\ln K$, e só se anula no caso particular $K=1$. A relação geral entre os dois é $\Delta G=\Delta G^{\circ}+RT\ln Q$.`,
  },
  {
    topico: T,
    subtopico: "Segunda lei e entropia do universo",
    dificuldade: "dificil",
    enunciado: R`A água congela espontaneamente a $-10\ ^{\circ}\text{C}$, embora o gelo seja mais ordenado que o líquido. A compatibilidade com a segunda lei vem de que:`,
    correta: R`a entropia da vizinhança cresce mais que a do sistema diminui`,
    distratores: [
      R`a entropia do sistema na verdade aumenta ao congelar`,
      R`a segunda lei não se aplica a processos abaixo de zero`,
      R`o congelamento ocorre com variação de entalpia positiva`,
      R`a entropia do universo permanece rigorosamente constante`,
    ],
    resolucao: R`O critério de espontaneidade é $\Delta S_{\text{universo}}=\Delta S_{\text{sist}}+\Delta S_{\text{viz}}>0$. O congelamento tem $\Delta S_{\text{sist}}<0$, mas é exotérmico, e o calor liberado se dissipa na vizinhança, aumentando sua entropia em $-\Delta H/T$. A $-10\ ^{\circ}\text{C}$ esse ganho supera a perda do sistema e a soma é positiva. Acima de $0\ ^{\circ}\text{C}$ a situação se inverte, e o processo espontâneo passa a ser a fusão — o ponto de fusão é exatamente a temperatura em que a soma se anula.`,
  },
  {
    topico: T,
    subtopico: "Espontaneidade e os sinais de entalpia e entropia",
    dificuldade: "dificil",
    enunciado: R`Uma reação tem $\Delta H<0$ e $\Delta S<0$. Sobre sua espontaneidade, conclui-se que ela é:`,
    correta: R`espontânea apenas a temperaturas baixas`,
    distratores: [
      R`espontânea apenas a temperaturas altas`,
      R`espontânea em qualquer temperatura`,
      R`não espontânea em qualquer temperatura`,
      R`espontânea somente na temperatura padrão`,
    ],
    resolucao: R`Em $\Delta G=\Delta H-T\Delta S$, o termo entálpico favorece a reação ($\Delta H<0$) e o entrópico a desfavorece, pois $-T\Delta S>0$. Como o peso do segundo cresce linearmente com a temperatura, existe um valor crítico $T=\Delta H/\Delta S$ acima do qual $\Delta G$ muda de sinal. Abaixo dele a entalpia domina e a reação é espontânea. É o caso de toda condensação e de sínteses como a da amônia, favorecidas termodinamicamente no frio — e por isso conduzidas com catalisador, não com calor extra.`,
  },
  {
    topico: T,
    subtopico: "Determinação da lei de velocidade por velocidades iniciais",
    dificuldade: "dificil",
    enunciado: R`Para $\text{A}+\text{B}\rightarrow\text{P}$ mediram-se, com $[\text{A}]$ e $[\text{B}]$ em mol/L e $v$ em mol/(L·s): $(0{,}10;\,0{,}10;\,2{,}0\times 10^{-3})$, $(0{,}20;\,0{,}10;\,8{,}0\times 10^{-3})$ e $(0{,}10;\,0{,}20;\,4{,}0\times 10^{-3})$. Determine a constante de velocidade.`,
    correta: R`$2{,}0$ L²/(mol²·s)`,
    distratores: [
      R`$0{,}20$ L²/(mol²·s)`,
      R`$20{,}0$ L²/(mol²·s)`,
      R`$0{,}020$ L²/(mol²·s)`,
      R`$200{,}0$ L²/(mol²·s)`,
    ],
    resolucao: R`Comparando os dois primeiros ensaios, $[\text{B}]$ é constante e dobrar $[\text{A}]$ quadruplica $v$: a ordem em $\text{A}$ é $2$. Entre o primeiro e o terceiro, dobrar $[\text{B}]$ apenas dobra $v$: a ordem em $\text{B}$ é $1$. A lei é $v=k[\text{A}]^{2}[\text{B}]$, de terceira ordem global. Substituindo o primeiro ensaio, $k=\dfrac{2{,}0\times 10^{-3}}{\left(0{,}10\right)^{2}\left(0{,}10\right)}=\dfrac{2{,}0\times 10^{-3}}{1{,}0\times 10^{-3}}=2{,}0$ L²/(mol²·s).`,
  },
  {
    topico: T,
    subtopico: "Cinética de segunda ordem",
    dificuldade: "dificil",
    enunciado: R`Uma reação de segunda ordem em relação a $\text{A}$ tem $k=0{,}20$ L/(mol·min). Partindo de $[\text{A}]_0=0{,}50$ mol/L, determine o tempo necessário para que a concentração caia a $0{,}10$ mol/L.`,
    correta: R`$40$ min`,
    distratores: [R`$20$ min`, R`$80$ min`, R`$25$ min`, R`$16$ min`],
    resolucao: R`A lei integrada de segunda ordem é $\dfrac{1}{[\text{A}]}=\dfrac{1}{[\text{A}]_0}+kt$. Substituindo, $\dfrac{1}{0{,}10}-\dfrac{1}{0{,}50}=10-2=8{,}0$, que deve igualar $kt=0{,}20\,t$. Logo $t=40$ min. Note a diferença essencial em relação à primeira ordem: aqui a meia-vida não é constante, pois depende de $[\text{A}]_0$, e a reação vai ficando cada vez mais lenta à medida que o reagente se esgota.`,
  },
  {
    topico: T,
    subtopico: "Meias-vidas sucessivas em primeira ordem",
    dificuldade: "dificil",
    enunciado: R`Uma reação de primeira ordem tem meia-vida de $30$ min. Determine a porcentagem do reagente que ainda resta após $2{,}0$ h de reação.`,
    correta: R`$6{,}25\%$`,
    distratores: [R`$12{,}50\%$`, R`$25{,}00\%$`, R`$3{,}13\%$`, R`$50{,}00\%$`],
    resolucao: R`Em $2{,}0$ h cabem $\dfrac{120}{30}=4$ meias-vidas. Em processos de primeira ordem cada meia-vida reduz a concentração à metade, independentemente do valor absoluto dela, de modo que resta $\left(\tfrac12\right)^{4}=\tfrac{1}{16}=0{,}0625$, ou $6{,}25\%$. Chegar-se-ia ao mesmo resultado por $k=\dfrac{\ln 2}{30}=0{,}0231$ min$^{-1}$ e $[\text{A}]/[\text{A}]_0=e^{-0{,}0231\times 120}$.`,
  },
  {
    topico: T,
    subtopico: "Energia de ativação pela equação de Arrhenius",
    dificuldade: "dificil",
    enunciado: R`A constante de velocidade de uma reação dobra ao se elevar a temperatura de $300$ K para $310$ K. Determine a energia de ativação, usando $R=8{,}314$ J/(mol·K) e $\ln 2=0{,}693$.`,
    correta: R`$53{,}6$ kJ/mol`,
    distratores: [R`$26{,}8$ kJ/mol`, R`$107{,}2$ kJ/mol`, R`$5{,}36$ kJ/mol`, R`$80{,}4$ kJ/mol`],
    resolucao: R`A forma de dois pontos da equação de Arrhenius é $\ln\dfrac{k_2}{k_1}=\dfrac{E_a}{R}\left(\dfrac{1}{T_1}-\dfrac{1}{T_2}\right)$. O fator entre parênteses vale $\dfrac{1}{300}-\dfrac{1}{310}=1{,}075\times 10^{-4}$ K$^{-1}$. Então $E_a=\dfrac{8{,}314\times 0{,}693}{1{,}075\times 10^{-4}}\approx 5{,}36\times 10^{4}$ J/mol, isto é, $53{,}6$ kJ/mol. Esse valor, próximo de $50$ kJ/mol, é a origem da regra prática de que dez graus a mais dobram a velocidade de muitas reações.`,
  },
  {
    topico: T,
    subtopico: "Efeito do catalisador sobre a velocidade",
    dificuldade: "dificil",
    enunciado: R`Um catalisador reduz a energia de ativação de uma reação de $100$ kJ/mol para $75$ kJ/mol. Determine por qual fator a velocidade aumenta a $298$ K, mantidos iguais o fator pré-exponencial e as concentrações. Use $R=8{,}314$ J/(mol·K).`,
    correta: R`$2{,}4\times 10^{4}$`,
    distratores: [
      R`$1{,}3\times 10^{2}$`,
      R`$4{,}2\times 10^{-5}$`,
      R`$2{,}4\times 10^{2}$`,
      R`$1{,}0\times 10^{3}$`,
    ],
    resolucao: R`A razão entre as constantes é $\dfrac{k_{\text{cat}}}{k}=e^{\left(E_a-E_a'\right)/RT}=e^{25\,000/\left(8{,}314\times 298\right)}=e^{10{,}09}\approx 2{,}4\times 10^{4}$. Uma redução aparentemente modesta de $25$ kJ/mol acelera a reação dezenas de milhares de vezes, porque a dependência é exponencial. Vale lembrar que o catalisador abaixa igualmente a barreira da reação inversa, de modo que a constante de equilíbrio permanece intacta.`,
  },
  {
    topico: T,
    subtopico: "Lei de velocidade a partir da etapa lenta",
    dificuldade: "dificil",
    enunciado: R`Propõe-se para $\text{NO}_2(g)+\text{CO}(g)\rightarrow\text{NO}(g)+\text{CO}_2(g)$ o mecanismo: etapa lenta $\text{NO}_2+\text{NO}_2\rightarrow\text{NO}_3+\text{NO}$; etapa rápida $\text{NO}_3+\text{CO}\rightarrow\text{NO}_2+\text{CO}_2$. Determine a lei de velocidade prevista.`,
    correta: R`$v=k[\text{NO}_2]^{2}$`,
    distratores: [
      R`$v=k[\text{NO}_2][\text{CO}]$`,
      R`$v=k[\text{NO}_2]^{2}[\text{CO}]$`,
      R`$v=k[\text{NO}_3][\text{CO}]$`,
      R`$v=k[\text{NO}_2]$`,
    ],
    resolucao: R`A velocidade global é imposta pela etapa mais lenta, e para uma etapa elementar os expoentes coincidem com os coeficientes: $v=k[\text{NO}_2]^{2}$. O $\text{CO}$, embora apareça na equação global, participa apenas de uma etapa rápida posterior e não influencia a velocidade — previsão contraintuitiva que a experiência confirma em baixas temperaturas. O $\text{NO}_3$ é intermediário e nunca pode figurar na lei de velocidade final.`,
  },
  {
    topico: T,
    subtopico: "Mecanismo com pré-equilíbrio rápido",
    dificuldade: "dificil",
    enunciado: R`Para $2\text{NO}(g)+\text{O}_2(g)\rightarrow 2\text{NO}_2(g)$ propõe-se: equilíbrio rápido $2\text{NO}\rightleftharpoons\text{N}_2\text{O}_2$; etapa lenta $\text{N}_2\text{O}_2+\text{O}_2\rightarrow 2\text{NO}_2$. Determine a lei de velocidade prevista.`,
    correta: R`$v=k[\text{NO}]^{2}[\text{O}_2]$`,
    distratores: [
      R`$v=k[\text{NO}][\text{O}_2]$`,
      R`$v=k[\text{N}_2\text{O}_2][\text{O}_2]$`,
      R`$v=k[\text{NO}]^{2}$`,
      R`$v=k[\text{NO}]^{2}[\text{O}_2]^{2}$`,
    ],
    resolucao: R`A etapa lenta dá $v=k_2[\text{N}_2\text{O}_2][\text{O}_2]$, mas o intermediário não pode permanecer na expressão. Do pré-equilíbrio, $K=\dfrac{[\text{N}_2\text{O}_2]}{[\text{NO}]^{2}}$, ou seja, $[\text{N}_2\text{O}_2]=K[\text{NO}]^{2}$. Substituindo, $v=k_2K[\text{NO}]^{2}[\text{O}_2]=k[\text{NO}]^{2}[\text{O}_2]$, de terceira ordem global. Esse mecanismo explica ainda a curiosidade de a reação ficar mais lenta ao se aquecer: o pré-equilíbrio exotérmico se desloca para o $\text{NO}$.`,
  },
  {
    topico: T,
    subtopico: "Ação do catalisador sobre equilíbrio e entalpia",
    dificuldade: "dificil",
    enunciado: R`Ao se adicionar um catalisador a um sistema reacional em condições fixas, permanecem inalterados:`,
    correta: R`$\Delta H$ e a constante de equilíbrio`,
    distratores: [
      R`a energia de ativação e $\Delta H$`,
      R`a constante de velocidade e $\Delta H$`,
      R`a energia de ativação e a constante de equilíbrio`,
      R`o tempo para atingir o equilíbrio e $\Delta H$`,
    ],
    resolucao: R`O catalisador oferece um caminho alternativo de menor energia de ativação, acelerando igualmente a reação direta e a inversa; por isso o equilíbrio é alcançado mais depressa, mas com a mesma composição final. Entalpia e energia livre são funções de estado, determinadas apenas pelos estados inicial e final, e independem do caminho: $\Delta H$ não muda, e como $\Delta G^{\circ}=-RT\ln K$, a constante de equilíbrio tampouco.`,
  },
  {
    topico: T,
    subtopico: "Molecularidade e ordem de reação",
    dificuldade: "medio",
    enunciado: R`Sobre a relação entre a equação química global e a lei de velocidade de uma reação, é correto afirmar que a ordem de reação:`,
    correta: R`é determinada experimentalmente`,
    distratores: [
      R`é sempre igual à soma dos coeficientes`,
      R`coincide com a molecularidade global`,
      R`é sempre um número inteiro positivo`,
      R`independe do mecanismo da reação`,
    ],
    resolucao: R`Só em uma etapa elementar os expoentes da lei de velocidade coincidem com os coeficientes estequiométricos. Numa reação global, que quase sempre é a soma de várias etapas, a lei precisa ser obtida por medidas de velocidade — e pode resultar fracionária, nula ou até negativa em relação a alguma espécie. Molecularidade é conceito aplicável apenas a etapas elementares e conta as partículas que colidem; ordem é uma descrição empírica do comportamento observado.`,
  },
  {
    topico: T,
    subtopico: "Teoria das colisões e fator de orientação",
    dificuldade: "medio",
    enunciado: R`Num gás, o número de colisões por segundo é ordens de grandeza maior que o número de reações efetivamente ocorridas. Além da energia insuficiente, o outro motivo dessa discrepância é:`,
    correta: R`a orientação inadequada das moléculas na colisão`,
    distratores: [
      R`a repulsão eletrostática entre as moléculas`,
      R`a diferença de massa entre os reagentes`,
      R`a baixa concentração dos reagentes`,
      R`a ausência de catalisador no meio`,
    ],
    resolucao: R`Para que a colisão seja produtiva, as moléculas precisam chegar com energia igual ou superior à de ativação e ainda com as regiões reativas voltadas uma para a outra. Em reações entre moléculas grandes, a fração de orientações favoráveis pode ser minúscula, e é isso que o fator estérico da equação de Arrhenius contabiliza no termo pré-exponencial. Concentração e catálise alteram o número de colisões ou a barreira, não essa fração geométrica.`,
  },
  {
    topico: T,
    subtopico: "Conversão entre Kc e Kp",
    dificuldade: "dificil",
    enunciado: R`Para $2\text{SO}_2(g)+\text{O}_2(g)\rightleftharpoons 2\text{SO}_3(g)$ tem-se $K_c=280{,}0$ a $1000$ K. Determine $K_p$, usando $R=0{,}0821$ atm·L/(mol·K).`,
    correta: R`$3{,}4$`,
    distratores: [R`$34{,}1$`, R`$0{,}34$`, R`$280{,}0$`, R`$23{,}0$`],
    resolucao: R`Vale $K_p=K_c\left(RT\right)^{\Delta n}$, com $\Delta n=2-3=-1$. Então $K_p=\dfrac{280{,}0}{0{,}0821\times 1000}=\dfrac{280{,}0}{82{,}1}\approx 3{,}4$. O expoente negativo reflete a contração do número de mols gasosos. Quando $\Delta n=0$ as duas constantes coincidem numericamente, o que ocorre, por exemplo, no equilíbrio entre $\text{H}_2$, $\text{I}_2$ e $\text{HI}$.`,
  },
  {
    topico: T,
    subtopico: "Quociente de reação e sentido do deslocamento",
    dificuldade: "dificil",
    enunciado: R`No equilíbrio $\text{H}_2(g)+\text{I}_2(g)\rightleftharpoons 2\text{HI}(g)$, com $K_c=50$, um recipiente contém as três espécies a $0{,}10$ mol/L cada. O sistema irá:`,
    correta: R`deslocar-se no sentido dos produtos`,
    distratores: [
      R`deslocar-se no sentido dos reagentes`,
      R`permanecer em equilíbrio`,
      R`consumir todo o iodo presente`,
      R`aumentar o valor de sua constante`,
    ],
    resolucao: R`Calcule o quociente com as concentrações do momento: $Q=\dfrac{\left(0{,}10\right)^{2}}{\left(0{,}10\right)\left(0{,}10\right)}=1$. Como $Q<K_c$, faltam produtos em relação à situação de equilíbrio, e a reação avança no sentido direto até que $Q$ cresça e iguale $50$. O valor da constante não muda: só a temperatura pode alterá-la. Se fosse $Q>K$, o sistema retrocederia.`,
  },
  {
    topico: T,
    subtopico: "Cálculo de constante de equilíbrio por tabela ICE",
    dificuldade: "dificil",
    enunciado: R`Em um recipiente de $1{,}0$ L colocam-se $1{,}00$ mol de $\text{H}_2$ e $1{,}00$ mol de $\text{I}_2$. No equilíbrio encontram-se $1{,}56$ mol de $\text{HI}$. Determine $K_c$ da reação $\text{H}_2(g)+\text{I}_2(g)\rightleftharpoons 2\text{HI}(g)$.`,
    correta: R`$50{,}3$`,
    distratores: [R`$7{,}1$`, R`$25{,}1$`, R`$100{,}6$`, R`$2{,}4$`],
    resolucao: R`Pela estequiometria, formar $1{,}56$ mol de $\text{HI}$ consome $0{,}78$ mol de cada reagente, restando $1{,}00-0{,}78=0{,}22$ mol/L de $\text{H}_2$ e de $\text{I}_2$. Então $K_c=\dfrac{\left(1{,}56\right)^{2}}{\left(0{,}22\right)\left(0{,}22\right)}=\dfrac{2{,}434}{0{,}0484}\approx 50{,}3$. O erro mais comum é subtrair $1{,}56$ dos reagentes, esquecendo o coeficiente $2$ do produto, o que levaria a um valor completamente diferente.`,
  },
  {
    topico: T,
    subtopico: "Le Chatelier: adição de gás inerte a volume constante",
    dificuldade: "dificil",
    enunciado: R`Ao sistema em equilíbrio $\text{N}_2(g)+3\text{H}_2(g)\rightleftharpoons 2\text{NH}_3(g)$, contido num recipiente rígido, injeta-se argônio. O efeito sobre o equilíbrio é:`,
    correta: R`nenhum deslocamento`,
    distratores: [
      R`deslocamento para a amônia`,
      R`deslocamento para os reagentes`,
      R`aumento do valor de $K_p$`,
      R`diminuição do valor de $K_c$`,
    ],
    resolucao: R`O argônio não participa da reação e, a volume constante, não altera as concentrações nem as pressões parciais das espécies envolvidas. A pressão total sobe, mas é o quociente calculado com as pressões parciais que determina o deslocamento, e ele permanece igual a $K$. Se, em vez disso, o gás inerte fosse acrescentado mantendo a pressão total constante — o que exigiria expandir o volume —, o equilíbrio se deslocaria para o lado de maior número de mols gasosos.`,
  },
  {
    topico: T,
    subtopico: "Le Chatelier: pressão em reação sem variação de mols",
    dificuldade: "dificil",
    enunciado: R`Comprimindo-se à metade o volume do sistema $\text{H}_2(g)+\text{I}_2(g)\rightleftharpoons 2\text{HI}(g)$, em equilíbrio e a temperatura constante, observa-se:`,
    correta: R`nenhum deslocamento do equilíbrio`,
    distratores: [
      R`deslocamento no sentido do $\text{HI}$`,
      R`deslocamento no sentido dos reagentes`,
      R`aumento da constante de equilíbrio`,
      R`diminuição da constante de equilíbrio`,
    ],
    resolucao: R`Reduzir o volume dobra todas as concentrações. No quociente $Q=\dfrac{[\text{HI}]^{2}}{[\text{H}_2][\text{I}_2]}$, o numerador é multiplicado por $4$ e o denominador também, de modo que $Q$ continua igual a $K_c$ e nada se desloca. Isso acontece sempre que $\Delta n_{\text{gás}}=0$. Para reações com $\Delta n\neq 0$, a compressão favorece o lado com menos mols de gás.`,
  },
  {
    topico: T,
    subtopico: "pH de solução de base forte diprótica",
    dificuldade: "dificil",
    enunciado: R`Determine o pH de uma solução aquosa de $\text{Ba(OH)}_2$ de concentração $5{,}0\times 10^{-3}$ mol/L, a $25\ ^{\circ}\text{C}$.`,
    correta: R`$12{,}00$`,
    distratores: [R`$11{,}70$`, R`$2{,}30$`, R`$2{,}00$`, R`$12{,}30$`],
    resolucao: R`Cada fórmula unitária libera dois íons hidróxido, de modo que $[\text{OH}^{-}]=2\times 5{,}0\times 10^{-3}=1{,}0\times 10^{-2}$ mol/L. Daí $\text{pOH}=-\log\left(1{,}0\times 10^{-2}\right)=2{,}00$ e, como $\text{pH}+\text{pOH}=14$ a $25\ ^{\circ}\text{C}$, $\text{pH}=12{,}00$. Ignorar o fator $2$ levaria a $11{,}70$; confundir pH com pOH levaria a $2{,}00$.`,
  },
  {
    topico: T,
    subtopico: "pH de ácido fraco a partir do Ka",
    dificuldade: "dificil",
    enunciado: R`Determine o pH de uma solução $0{,}20$ mol/L de ácido acético, cujo $K_a$ vale $1{,}8\times 10^{-5}$.`,
    correta: R`$2{,}72$`,
    distratores: [R`$4{,}74$`, R`$3{,}02$`, R`$2{,}42$`, R`$5{,}44$`],
    resolucao: R`Montando a tabela de equilíbrio com $x=[\text{H}^{+}]$ e supondo $x\ll 0{,}20$, tem-se $K_a\approx\dfrac{x^{2}}{0{,}20}$, logo $x=\sqrt{1{,}8\times 10^{-5}\times 0{,}20}=\sqrt{3{,}6\times 10^{-6}}=1{,}9\times 10^{-3}$ mol/L. Então $\text{pH}=-\log\left(1{,}9\times 10^{-3}\right)\approx 2{,}72$. A aproximação se justifica: $x$ é menos de $1\%$ da concentração inicial. O valor $4{,}74$ é o $\text{p}K_a$, que só seria o pH numa solução tampão equimolar.`,
  },
  {
    topico: T,
    subtopico: "Lei da diluição de Ostwald",
    dificuldade: "dificil",
    enunciado: R`Uma solução de ácido fraco é diluída a temperatura constante. Sobre o grau de ionização $\alpha$ e a concentração de $\text{H}^{+}$, ocorre que:`,
    correta: R`$\alpha$ aumenta e $[\text{H}^{+}]$ diminui`,
    distratores: [
      R`$\alpha$ diminui e $[\text{H}^{+}]$ aumenta`,
      R`ambos aumentam`,
      R`ambos diminuem`,
      R`$\alpha$ permanece constante e $[\text{H}^{+}]$ diminui`,
    ],
    resolucao: R`Da lei de Ostwald, $K_a=\dfrac{\alpha^{2}C}{1-\alpha}$, com $K_a$ fixo: se $C$ cai, $\alpha$ precisa crescer. Isso é o princípio de Le Chatelier aplicado à ionização, que produz mais partículas e por isso é favorecida pela diluição. Ainda assim, $[\text{H}^{+}]=\alpha C$ diminui, porque a queda de $C$ é proporcionalmente maior que o ganho de $\alpha$ — diluir uma solução ácida sempre eleva o pH, por mais que a ionização percentual aumente.`,
  },
  {
    topico: T,
    subtopico: "pH de solução-tampão pela equação de Henderson-Hasselbalch",
    dificuldade: "dificil",
    enunciado: R`Determine o pH de um tampão que contém ácido acético $0{,}20$ mol/L e acetato de sódio $0{,}30$ mol/L, sabendo que $\text{p}K_a=4{,}74$ e $\log 1{,}5=0{,}18$.`,
    correta: R`$4{,}92$`,
    distratores: [R`$4{,}56$`, R`$4{,}74$`, R`$5{,}22$`, R`$4{,}44$`],
    resolucao: R`A equação de Henderson-Hasselbalch dá $\text{pH}=\text{p}K_a+\log\dfrac{[\text{base}]}{[\text{ácido}]}=4{,}74+\log\dfrac{0{,}30}{0{,}20}=4{,}74+0{,}18=4{,}92$. Como há mais base conjugada que ácido, o pH fica acima do $\text{p}K_a$, como esperado. Inverter a razão produz $4{,}56$, erro frequente; note ainda que o pH do tampão depende apenas da razão entre as concentrações, e não de seus valores absolutos.`,
  },
  {
    topico: T,
    subtopico: "Resposta de um tampão à adição de base forte",
    dificuldade: "dificil",
    enunciado: R`Um litro de tampão contém $0{,}40$ mol de ácido acético e $0{,}40$ mol de acetato de sódio. Determine o pH após a adição de $0{,}10$ mol de $\text{NaOH}$, com $\text{p}K_a=4{,}74$ e $\log\left(\tfrac{5}{3}\right)=0{,}22$.`,
    correta: R`$4{,}96$`,
    distratores: [R`$4{,}52$`, R`$4{,}74$`, R`$5{,}26$`, R`$13{,}00$`],
    resolucao: R`O hidróxido consome quantidade equivalente de ácido e produz a mesma quantidade de base conjugada: o ácido cai para $0{,}40-0{,}10=0{,}30$ mol e o acetato sobe para $0{,}40+0{,}10=0{,}50$ mol. Então $\text{pH}=4{,}74+\log\dfrac{0{,}50}{0{,}30}=4{,}74+0{,}22=4{,}96$. A variação é de apenas $0{,}22$ unidade, contra os mais de $12$ que a mesma adição provocaria em água pura — é essa resistência que define um tampão.`,
  },
  {
    topico: T,
    subtopico: "pH no ponto de equivalência de titulação de ácido fraco",
    dificuldade: "dificil",
    enunciado: R`Titulam-se $25{,}0$ mL de ácido acético $0{,}10$ mol/L ($K_a=1{,}8\times 10^{-5}$) com $\text{NaOH}$ $0{,}10$ mol/L. Determine o pH no ponto de equivalência, lembrando que o volume final é o dobro do inicial.`,
    correta: R`$8{,}72$`,
    distratores: [R`$7{,}00$`, R`$5{,}28$`, R`$9{,}26$`, R`$8{,}22$`],
    resolucao: R`No ponto de equivalência todo o ácido virou acetato, e a diluição pelo volume de titulante deixa $[\text{CH}_3\text{COO}^{-}]=0{,}050$ mol/L. Esse ânion hidrolisa com $K_b=\dfrac{K_w}{K_a}=\dfrac{1{,}0\times 10^{-14}}{1{,}8\times 10^{-5}}=5{,}6\times 10^{-10}$. Daí $[\text{OH}^{-}]=\sqrt{5{,}6\times 10^{-10}\times 0{,}050}=5{,}3\times 10^{-6}$ mol/L, $\text{pOH}=5{,}28$ e $\text{pH}=8{,}72$. O ponto de equivalência de ácido fraco com base forte é sempre básico — por isso se usa fenolftaleína, e não azul de bromotimol.`,
  },
  {
    topico: T,
    subtopico: "Solubilidade molar a partir do produto de solubilidade",
    dificuldade: "dificil",
    enunciado: R`O fluoreto de cálcio tem $K_{ps}=3{,}9\times 10^{-11}$ a $25\ ^{\circ}\text{C}$. Determine sua solubilidade molar em água pura.`,
    correta: R`$2{,}1\times 10^{-4}$ mol/L`,
    distratores: [
      R`$6{,}2\times 10^{-6}$ mol/L`,
      R`$3{,}4\times 10^{-4}$ mol/L`,
      R`$1{,}6\times 10^{-4}$ mol/L`,
      R`$2{,}1\times 10^{-6}$ mol/L`,
    ],
    resolucao: R`Dissolvendo $s$ mol/L de $\text{CaF}_2$, obtêm-se $s$ mol/L de $\text{Ca}^{2+}$ e $2s$ mol/L de $\text{F}^{-}$. Então $K_{ps}=s\left(2s\right)^{2}=4s^{3}$, de onde $s^{3}=\dfrac{3{,}9\times 10^{-11}}{4}=9{,}75\times 10^{-12}$ e $s\approx 2{,}1\times 10^{-4}$ mol/L. Esquecer o coeficiente $2$ do fluoreto — e com ele o fator $4$ — é o deslize clássico, e faz a solubilidade parecer maior do que é.`,
  },
  {
    topico: T,
    subtopico: "Efeito do íon comum sobre a solubilidade",
    dificuldade: "dificil",
    enunciado: R`O cloreto de prata tem $K_{ps}=1{,}8\times 10^{-10}$. Determine sua solubilidade molar numa solução de $\text{NaCl}$ $0{,}10$ mol/L.`,
    correta: R`$1{,}8\times 10^{-9}$ mol/L`,
    distratores: [
      R`$1{,}3\times 10^{-5}$ mol/L`,
      R`$1{,}8\times 10^{-10}$ mol/L`,
      R`$1{,}8\times 10^{-11}$ mol/L`,
      R`$5{,}6\times 10^{-6}$ mol/L`,
    ],
    resolucao: R`Seja $s$ a solubilidade nessas condições: $[\text{Ag}^{+}]=s$ e $[\text{Cl}^{-}]=0{,}10+s\approx 0{,}10$, já que o cloreto proveniente do sal domina largamente. Então $s=\dfrac{K_{ps}}{0{,}10}=1{,}8\times 10^{-9}$ mol/L, cerca de sete mil vezes menor que em água pura, onde seria $\sqrt{K_{ps}}=1{,}3\times 10^{-5}$ mol/L. O efeito do íon comum é a aplicação direta do princípio de Le Chatelier ao equilíbrio de dissolução.`,
  },
  {
    topico: T,
    subtopico: "Previsão de precipitação pelo quociente iônico",
    dificuldade: "dificil",
    enunciado: R`Misturam-se volumes iguais de $\text{Ca(NO}_3)_2$ $2{,}0\times 10^{-3}$ mol/L e $\text{NaF}$ $2{,}0\times 10^{-3}$ mol/L. Determine o quociente iônico $Q$ do $\text{CaF}_2$ logo após a mistura.`,
    correta: R`$1{,}0\times 10^{-9}$`,
    distratores: [
      R`$8{,}0\times 10^{-9}$`,
      R`$4{,}0\times 10^{-6}$`,
      R`$1{,}0\times 10^{-6}$`,
      R`$2{,}0\times 10^{-9}$`,
    ],
    resolucao: R`A mistura de volumes iguais reduz à metade cada concentração: $[\text{Ca}^{2+}]=[\text{F}^{-}]=1{,}0\times 10^{-3}$ mol/L. Então $Q=[\text{Ca}^{2+}][\text{F}^{-}]^{2}=\left(1{,}0\times 10^{-3}\right)\left(1{,}0\times 10^{-3}\right)^{2}=1{,}0\times 10^{-9}$. Como esse valor excede o $K_{ps}=3{,}9\times 10^{-11}$, forma-se precipitado até que o produto iônico caia ao valor da constante. Esquecer a diluição pela metade é o erro mais frequente.`,
  },
  {
    topico: T,
    subtopico: "Equação de Nernst",
    dificuldade: "dificil",
    enunciado: R`A pilha de Daniell tem $E^{\circ}=1{,}10$ V. Calcule seu potencial quando $[\text{Zn}^{2+}]=1{,}0$ mol/L e $[\text{Cu}^{2+}]=0{,}010$ mol/L, usando $E=E^{\circ}-\dfrac{0{,}0592}{n}\log Q$.`,
    correta: R`$1{,}04$ V`,
    distratores: [R`$1{,}16$ V`, R`$1{,}10$ V`, R`$0{,}99$ V`, R`$1{,}28$ V`],
    resolucao: R`A reação global é $\text{Zn}+\text{Cu}^{2+}\rightarrow\text{Zn}^{2+}+\text{Cu}$, com $n=2$ e $Q=\dfrac{[\text{Zn}^{2+}]}{[\text{Cu}^{2+}]}=\dfrac{1{,}0}{0{,}010}=100$. Então $E=1{,}10-\dfrac{0{,}0592}{2}\times 2=1{,}10-0{,}059=1{,}04$ V. O potencial cai porque o reagente está escasso em relação ao produto — exatamente o que acontece com uma pilha ao longo do uso, até que $Q$ alcance $K$ e $E$ se anule, quando a pilha está descarregada.`,
  },
  {
    topico: T,
    subtopico: "Energia livre a partir do potencial de célula",
    dificuldade: "dificil",
    enunciado: R`Determine $\Delta G^{\circ}$ da reação global da pilha de Daniell, que envolve $2$ mols de elétrons e tem $E^{\circ}=1{,}10$ V. Use $F=96\,500$ C/mol.`,
    correta: R`$-212$ kJ`,
    distratores: [R`$-106$ kJ`, R`$+212$ kJ`, R`$-424$ kJ`, R`$-2{,}12$ kJ`],
    resolucao: R`Vale $\Delta G^{\circ}=-nFE^{\circ}=-2\times 96\,500\times 1{,}10=-2{,}12\times 10^{5}$ J, isto é, $-212$ kJ. O sinal negativo confirma a espontaneidade, coerente com um potencial de célula positivo. Esse número representa o trabalho elétrico máximo extraível por mol de reação; qualquer corrente real, com dissipação ôhmica, entrega menos que isso.`,
  },
  {
    topico: T,
    subtopico: "Eletrólise e volume de gás produzido",
    dificuldade: "dificil",
    enunciado: R`Na eletrólise da água acidulada, uma corrente de $1{,}93$ A circula durante $1000$ s. Determine o volume de $\text{H}_2$ obtido nas CNTP, com $F=96\,500$ C/mol e volume molar $22{,}4$ L/mol.`,
    correta: R`$0{,}224$ L`,
    distratores: [R`$0{,}448$ L`, R`$0{,}112$ L`, R`$1{,}120$ L`, R`$0{,}022$ L`],
    resolucao: R`A carga total é $Q=it=1{,}93\times 1000=1930$ C, equivalente a $\dfrac{1930}{96\,500}=0{,}0200$ mol de elétrons. No cátodo ocorre $2\text{H}^{+}+2e^{-}\rightarrow\text{H}_2$, de modo que cada mol de hidrogênio consome dois mols de elétrons: formam-se $0{,}0100$ mol. O volume é $0{,}0100\times 22{,}4=0{,}224$ L. Esquecer o fator $2$ da semirreação leva a $0{,}448$ L, o dobro do correto.`,
  },
  {
    topico: T,
    subtopico: "Dependência da constante de equilíbrio com a temperatura",
    dificuldade: "dificil",
    enunciado: R`Para uma reação exotérmica em fase gasosa, o efeito de um aumento de temperatura sobre a constante de equilíbrio é:`,
    correta: R`$K$ diminui`,
    distratores: [
      R`$K$ aumenta`,
      R`$K$ não se altera`,
      R`$K$ tende a zero`,
      R`$K$ fica negativa`,
    ],
    resolucao: R`Pela equação de van't Hoff, $\dfrac{d\ln K}{dT}=\dfrac{\Delta H^{\circ}}{RT^{2}}$: com $\Delta H^{\circ}<0$, $\ln K$ decresce quando $T$ aumenta. A leitura qualitativa é a de Le Chatelier — o calor é um dos "produtos" e o aquecimento desloca o equilíbrio para os reagentes. A temperatura é a única perturbação capaz de alterar o valor de $K$; pressão, concentração e catalisador mudam apenas a composição do equilíbrio ou a rapidez com que ele é atingido.`,
  },
];
