// Lote 3 de Química Geral — Tópico 1: Estrutura Atômica e Tabela Periódica.
// Estilo Brown, "Química: A Ciência Central" (caps. 2, 6 e 7): maioria
// conceitual, mas com raciocínio encadeado — nada de pergunta de definição.
// Sem questões `facil`.
const R = String.raw;
const T = "Estrutura Atômica e Tabela Periódica";

export const questoes = [
  {
    topico: T,
    subtopico: "Massa atômica média e abundância isotópica",
    dificuldade: "dificil",
    enunciado: R`O boro natural é uma mistura de $^{10}\text{B}$ (massa $10{,}013$ u) e $^{11}\text{B}$ (massa $11{,}009$ u), e sua massa atômica tabelada é $10{,}81$ u. Determine a abundância do isótopo $^{11}\text{B}$.`,
    correta: R`$80{,}0\%$`,
    distratores: [R`$20{,}0\%$`, R`$75{,}0\%$`, R`$50{,}0\%$`, R`$60{,}0\%$`],
    resolucao: R`Seja $x$ a fração de $^{11}\text{B}$; a de $^{10}\text{B}$ é $1-x$. A massa média é a média ponderada pelas abundâncias: $11{,}009x+10{,}013(1-x)=10{,}81$. Desenvolvendo, $10{,}013+0{,}996x=10{,}81$, logo $x=\dfrac{0{,}797}{0{,}996}=0{,}800$, ou seja, $80{,}0\%$. A verificação rápida é notar que $10{,}81$ está muito mais perto de $11{,}009$ do que de $10{,}013$, de modo que o isótopo pesado tem de ser o majoritário — quem responde $20\%$ inverteu a ponderação.`,
  },
  {
    topico: T,
    subtopico: "Espectrometria de massas e padrão isotópico",
    dificuldade: "dificil",
    enunciado: R`O cloro natural contém $75\%$ de $^{35}\text{Cl}$ e $25\%$ de $^{37}\text{Cl}$. No espectro de massas do $\text{Cl}_2$ aparecem três picos, em $m/z$ iguais a $70$, $72$ e $74$. Determine a razão entre suas intensidades, nessa ordem.`,
    correta: R`$9:6:1$`,
    distratores: [R`$3:1:0$`, R`$1:2:1$`, R`$9:3:1$`, R`$6:9:1$`],
    resolucao: R`Cada molécula tem dois átomos sorteados independentemente. O pico $70$ exige dois $^{35}\text{Cl}$: $0{,}75^2=0{,}5625$. O pico $74$ exige dois $^{37}\text{Cl}$: $0{,}25^2=0{,}0625$. O pico $72$ é misto e pode ocorrer de duas maneiras ($^{35}\text{Cl}{-}^{37}\text{Cl}$ e $^{37}\text{Cl}{-}^{35}\text{Cl}$): $2\cdot 0{,}75\cdot 0{,}25=0{,}375$. Dividindo tudo por $0{,}0625$ obtém-se $9:6:1$. O erro típico é esquecer o fator $2$ do pico misto e concluir $9:3:1$.`,
  },
  {
    topico: T,
    subtopico: "Lei das proporções múltiplas",
    dificuldade: "dificil",
    enunciado: R`Dois óxidos de nitrogênio contêm, em massa, $63{,}6\%$ e $46{,}7\%$ de nitrogênio. Calcule a razão entre as massas de oxigênio combinadas com uma mesma massa de nitrogênio nos dois compostos (segundo composto em relação ao primeiro).`,
    correta: R`$2:1$`,
    distratores: [R`$1:2$`, R`$3:2$`, R`$1:1$`, R`$4:3$`],
    resolucao: R`Fixe $100$ g de cada composto. No primeiro há $63{,}6$ g de $\text{N}$ para $36{,}4$ g de $\text{O}$, isto é, $\dfrac{36{,}4}{63{,}6}=0{,}572$ g de $\text{O}$ por grama de $\text{N}$. No segundo, $\dfrac{53{,}3}{46{,}7}=1{,}141$ g de $\text{O}$ por grama de $\text{N}$. A razão é $\dfrac{1{,}141}{0{,}572}\approx 2$. Números inteiros pequenos como esse são exatamente o que enunciou a lei das proporções múltiplas de Dalton — os compostos são $\text{N}_2\text{O}$ e $\text{NO}$.`,
  },
  {
    topico: T,
    subtopico: "Experimento de Rutherford",
    dificuldade: "medio",
    enunciado: R`No experimento da folha de ouro, praticamente todas as partículas $\alpha$ atravessaram a lâmina sem desvio, mas uma fração ínfima retrocedeu em ângulos maiores que $90^{\circ}$. Se o modelo de Thomson (esfera de carga positiva difusa) estivesse correto, o resultado esperado seria:`,
    correta: R`somente desvios muito pequenos`,
    distratores: [
      R`retrocesso da maior parte do feixe`,
      R`absorção total das partículas`,
      R`desvios idênticos para todas elas`,
      R`emissão de elétrons pela folha`,
    ],
    resolucao: R`Com a carga positiva diluída por todo o volume do átomo, o campo elétrico sentido pela partícula $\alpha$ em qualquer trajetória seria fraco e aproximadamente compensado de todos os lados, produzindo apenas pequenas deflexões acumuladas. O retrocesso observado exige uma concentração de carga positiva e de massa num volume minúsculo, capaz de exercer uma força intensa num único encontro — o núcleo. A raridade do evento informa, além disso, que esse núcleo ocupa uma fração desprezível da área da folha.`,
  },
  {
    topico: T,
    subtopico: "Efeito fotoelétrico: energia cinética do elétron",
    dificuldade: "dificil",
    enunciado: R`A função trabalho do sódio metálico é $2{,}28$ eV. Incidindo sobre ele luz de comprimento de onda $400$ nm, determine a energia cinética máxima dos elétrons emitidos. Use $\lambda(\text{nm})=\dfrac{1240}{E(\text{eV})}$.`,
    correta: R`$0{,}82$ eV`,
    distratores: [R`$1{,}24$ eV`, R`$2{,}28$ eV`, R`$5{,}38$ eV`, R`$0{,}41$ eV`],
    resolucao: R`Primeiro converta o comprimento de onda em energia de fóton: $E=\dfrac{1240}{400}=3{,}10$ eV. A equação de Einstein para o efeito fotoelétrico dá $E_c=h\nu-\Phi=3{,}10-2{,}28=0{,}82$ eV. Note que a energia do fóton se reparte em duas parcelas: a mínima necessária para arrancar o elétron do metal ($\Phi$) e o excedente, que aparece como energia cinética. Aumentar a intensidade da luz aumentaria o número de elétrons emitidos, não essa energia.`,
  },
  {
    topico: T,
    subtopico: "Efeito fotoelétrico: comprimento de onda limiar",
    dificuldade: "dificil",
    enunciado: R`Um metal tem função trabalho de $4{,}50$ eV. Determine o maior comprimento de onda capaz de provocar emissão fotoelétrica nesse metal, usando $\lambda(\text{nm})=\dfrac{1240}{E(\text{eV})}$.`,
    correta: R`$276$ nm`,
    distratores: [R`$248$ nm`, R`$310$ nm`, R`$205$ nm`, R`$551$ nm`],
    resolucao: R`O limiar corresponde a elétrons emitidos com energia cinética nula, isto é, fóton com energia exatamente igual à função trabalho: $E=4{,}50$ eV. Então $\lambda=\dfrac{1240}{4{,}50}\approx 276$ nm, na região do ultravioleta. Qualquer comprimento de onda maior que esse carrega fótons menos energéticos e não produz corrente alguma, por mais intenso que seja o feixe — foi justamente essa independência em relação à intensidade que derrubou a descrição puramente ondulatória da luz.`,
  },
  {
    topico: T,
    subtopico: "Contagem de fótons de uma fonte luminosa",
    dificuldade: "dificil",
    enunciado: R`Um laser de hélio-neônio emite luz de $633$ nm com potência de $5{,}0$ mW. Calcule o número de fótons emitidos em $1{,}0$ s. Use $hc=1{,}986\times 10^{-25}$ J·m.`,
    correta: R`$1{,}6\times 10^{16}$`,
    distratores: [
      R`$3{,}1\times 10^{16}$`,
      R`$1{,}6\times 10^{19}$`,
      R`$8{,}0\times 10^{15}$`,
      R`$3{,}2\times 10^{17}$`,
    ],
    resolucao: R`A energia de um fóton é $E=\dfrac{hc}{\lambda}=\dfrac{1{,}986\times 10^{-25}}{6{,}33\times 10^{-7}}=3{,}14\times 10^{-19}$ J. Em $1{,}0$ s o laser entrega $5{,}0\times 10^{-3}$ J. O número de fótons é o quociente entre a energia total e a energia de cada um: $N=\dfrac{5{,}0\times 10^{-3}}{3{,}14\times 10^{-19}}\approx 1{,}6\times 10^{16}$. O valor enorme explica por que a granularidade da luz passa despercebida em experimentos macroscópicos.`,
  },
  {
    topico: T,
    subtopico: "Limite da série de Balmer",
    dificuldade: "dificil",
    enunciado: R`No átomo de hidrogênio ($E_n=-\dfrac{13{,}6}{n^2}$ eV), determine o menor comprimento de onda da série de Balmer, isto é, o limite das transições que terminam em $n=2$. Use $\lambda(\text{nm})=\dfrac{1240}{E(\text{eV})}$.`,
    correta: R`$365$ nm`,
    distratores: [R`$656$ nm`, R`$91$ nm`, R`$122$ nm`, R`$486$ nm`],
    resolucao: R`O menor comprimento de onda corresponde à maior energia liberada, ou seja, à transição que parte do nível mais alto possível, $n\to\infty$. Nesse caso $\Delta E=0-\left(-\dfrac{13{,}6}{2^2}\right)=3{,}40$ eV. Logo $\lambda=\dfrac{1240}{3{,}40}\approx 365$ nm. Esse é o ponto onde as linhas da série se acumulam e se fundem no contínuo; $91$ nm seria o limite análogo da série de Lyman, que termina em $n=1$.`,
  },
  {
    topico: T,
    subtopico: "Íons hidrogenoides e dependência em Z",
    dificuldade: "dificil",
    enunciado: R`Para íons com um único elétron vale $E_n=-13{,}6\,\dfrac{Z^2}{n^2}$ eV. Determine a energia necessária para arrancar o elétron do íon $\text{He}^{+}$ em seu estado fundamental.`,
    correta: R`$54{,}4$ eV`,
    distratores: [R`$13{,}6$ eV`, R`$27{,}2$ eV`, R`$6{,}8$ eV`, R`$108{,}8$ eV`],
    resolucao: R`Para o $\text{He}^{+}$ tem-se $Z=2$ e estado fundamental $n=1$, portanto $E_1=-13{,}6\cdot\dfrac{4}{1}=-54{,}4$ eV. A ionização leva o elétron a $E_\infty=0$, de modo que a energia exigida é $0-(-54{,}4)=54{,}4$ eV — quatro vezes a do hidrogênio, porque a energia escala com $Z^2$. Responder $27{,}2$ eV corresponde ao erro de escalar linearmente com $Z$.`,
  },
  {
    topico: T,
    subtopico: "Comprimento de onda de de Broglie do nêutron",
    dificuldade: "dificil",
    enunciado: R`Calcule o comprimento de onda de de Broglie de um nêutron térmico que se move a $2{,}2\times 10^{3}$ m/s. Use $h=6{,}626\times 10^{-34}$ J·s e $m_n=1{,}675\times 10^{-27}$ kg.`,
    correta: R`$1{,}8\times 10^{-10}$ m`,
    distratores: [
      R`$1{,}8\times 10^{-7}$ m`,
      R`$3{,}6\times 10^{-10}$ m`,
      R`$9{,}0\times 10^{-11}$ m`,
      R`$1{,}8\times 10^{-13}$ m`,
    ],
    resolucao: R`O momento linear vale $p=mv=\left(1{,}675\times 10^{-27}\right)\left(2{,}2\times 10^{3}\right)=3{,}69\times 10^{-24}$ kg·m/s. Então $\lambda=\dfrac{h}{p}=\dfrac{6{,}626\times 10^{-34}}{3{,}69\times 10^{-24}}\approx 1{,}8\times 10^{-10}$ m. O resultado é da ordem das distâncias interatômicas de um cristal, e é por isso que nêutrons lentos servem de sonda de difração para determinar estruturas — inclusive posições de átomos leves, que os raios X enxergam mal.`,
  },
  {
    topico: T,
    subtopico: "Princípio da incerteza de Heisenberg",
    dificuldade: "dificil",
    enunciado: R`Um elétron está confinado numa região de dimensão $1{,}0\times 10^{-10}$ m. Usando $\Delta x\cdot m\,\Delta v\ge\dfrac{h}{4\pi}$, com $h=6{,}626\times 10^{-34}$ J·s e $m_e=9{,}11\times 10^{-31}$ kg, estime a incerteza mínima em sua velocidade.`,
    correta: R`$5{,}8\times 10^{5}$ m/s`,
    distratores: [
      R`$5{,}8\times 10^{6}$ m/s`,
      R`$1{,}2\times 10^{6}$ m/s`,
      R`$2{,}9\times 10^{5}$ m/s`,
      R`$5{,}8\times 10^{4}$ m/s`,
    ],
    resolucao: R`Isolando, $\Delta v\ge\dfrac{h}{4\pi m\,\Delta x}=\dfrac{6{,}626\times 10^{-34}}{4\pi\left(9{,}11\times 10^{-31}\right)\left(1{,}0\times 10^{-10}\right)}$. O denominador vale $1{,}14\times 10^{-39}$, de modo que $\Delta v\approx 5{,}8\times 10^{5}$ m/s. A incerteza é comparável à própria velocidade típica do elétron no átomo: falar em trajetória bem definida para ele não tem sentido físico, e é esse o motivo pelo qual o orbital substitui a órbita de Bohr.`,
  },
  {
    topico: T,
    subtopico: "Conjuntos de números quânticos permitidos",
    dificuldade: "medio",
    enunciado: R`Considerando as restrições entre os números quânticos $\left(n,\ell,m_\ell,m_s\right)$, qual conjunto abaixo é impossível?`,
    correta: R`$\left(3,\,3,\,0,\,+\tfrac{1}{2}\right)$`,
    distratores: [
      R`$\left(3,\,2,\,-2,\,+\tfrac{1}{2}\right)$`,
      R`$\left(4,\,0,\,0,\,-\tfrac{1}{2}\right)$`,
      R`$\left(2,\,1,\,+1,\,-\tfrac{1}{2}\right)$`,
      R`$\left(5,\,4,\,-3,\,+\tfrac{1}{2}\right)$`,
    ],
    resolucao: R`As regras são $\ell=0,1,\dots,n-1$ e $m_\ell=-\ell,\dots,+\ell$, com $m_s=\pm\tfrac12$. No conjunto $\left(3,3,0,+\tfrac12\right)$ tem-se $\ell=n$, o que viola a primeira regra: com $n=3$ o máximo é $\ell=2$ (subnível $3d$). Todos os demais respeitam as três condições — inclusive $\left(5,4,-3,+\tfrac12\right)$, que descreve um elétron $5g$, subnível que existe formalmente ainda que não seja ocupado nos átomos do estado fundamental conhecidos.`,
  },
  {
    topico: T,
    subtopico: "Nós radiais e angulares de um orbital",
    dificuldade: "dificil",
    enunciado: R`Determine o número de nós radiais de um orbital $5p$ de um átomo hidrogenoide, lembrando que o número total de nós é $n-1$ e que $\ell$ deles são angulares.`,
    correta: R`$3$`,
    distratores: [R`$4$`, R`$2$`, R`$1$`, R`$5$`],
    resolucao: R`Para o orbital $5p$ tem-se $n=5$ e $\ell=1$. O número total de nós é $n-1=4$, dos quais $\ell=1$ é angular (o plano nodal que separa os dois lóbulos do orbital $p$). Restam $n-\ell-1=5-1-1=3$ nós radiais, isto é, três superfícies esféricas onde a densidade de probabilidade se anula. O número de nós radiais cresce com $n$ dentro de um mesmo subnível e é o que empurra a densidade eletrônica para longe do núcleo.`,
  },
  {
    topico: T,
    subtopico: "Penetração e blindagem em átomos polieletrônicos",
    dificuldade: "dificil",
    enunciado: R`Num átomo polieletrônico observa-se $E_{3s}<E_{3p}<E_{3d}$, embora no hidrogênio os três subníveis tenham a mesma energia. A causa dessa separação é:`,
    correta: R`maior penetração dos orbitais $s$`,
    distratores: [
      R`maior número de nós angulares do $s$`,
      R`repulsão entre elétrons de mesmo spin`,
      R`diferença de momento angular de spin`,
      R`aumento da carga nuclear com $\ell$`,
    ],
    resolucao: R`A função de distribuição radial do orbital $3s$ apresenta pequenos máximos muito próximos do núcleo, região onde os elétrons internos não conseguem blindar a carga nuclear. O elétron $3s$ portanto "vê" uma carga nuclear efetiva maior e fica mais estabilizado. O orbital $3p$ penetra menos, e o $3d$, com dois nós angulares, é praticamente expulso da vizinhança do núcleo. Como no hidrogênio não há outros elétrons para blindar, o efeito desaparece e a energia depende apenas de $n$.`,
  },
  {
    topico: T,
    subtopico: "Exceções à ordem de preenchimento",
    dificuldade: "medio",
    enunciado: R`Escreva a configuração eletrônica do átomo de cromo ($Z=24$) em seu estado fundamental.`,
    correta: R`$[\text{Ar}]3d^{5}4s^{1}$`,
    distratores: [
      R`$[\text{Ar}]3d^{4}4s^{2}$`,
      R`$[\text{Ar}]3d^{6}$`,
      R`$[\text{Ar}]3d^{3}4s^{2}4p^{1}$`,
      R`$[\text{Ar}]3d^{5}4s^{2}$`,
    ],
    resolucao: R`A regra de Aufbau prevê $[\text{Ar}]3d^{4}4s^{2}$, mas os subníveis $4s$ e $3d$ têm energias muito próximas, e a configuração observada é $[\text{Ar}]3d^{5}4s^{1}$. A promoção de um elétron $4s$ para o $3d$ é compensada pela estabilidade extra do subnível $d$ semipreenchido, com cinco elétrons de spins paralelos em orbitais distintos, que minimiza a repulsão elétron-elétron. O cobre exibe a mesma anomalia, alcançando o $3d$ completo.`,
  },
  {
    topico: T,
    subtopico: "Configuração eletrônica de cátion de metal de transição",
    dificuldade: "dificil",
    enunciado: R`Escreva a configuração eletrônica do íon $\text{Cu}^{2+}$, sabendo que $Z=29$.`,
    correta: R`$[\text{Ar}]3d^{9}$`,
    distratores: [
      R`$[\text{Ar}]3d^{7}4s^{2}$`,
      R`$[\text{Ar}]3d^{10}$`,
      R`$[\text{Ar}]3d^{8}4s^{1}$`,
      R`$[\text{Ar}]3d^{10}4s^{1}$`,
    ],
    resolucao: R`O cobre neutro é uma das exceções do bloco $d$: $[\text{Ar}]3d^{10}4s^{1}$. Na formação de cátions de metais de transição, os elétrons saem primeiro do subnível de maior número quântico principal, o $4s$, e só então do $3d$ — ao contrário da ordem de preenchimento. Retirando o único elétron $4s$ e um elétron $3d$, resta $[\text{Ar}]3d^{9}$, configuração com um elétron desemparelhado que explica o paramagnetismo e a cor azul dos sais de $\text{Cu}^{2+}$.`,
  },
  {
    topico: T,
    subtopico: "Elétrons desemparelhados e paramagnetismo",
    dificuldade: "medio",
    enunciado: R`Determine o número de elétrons desemparelhados no íon $\text{Co}^{2+}$ em campo fraco, sabendo que o cobalto tem $Z=27$.`,
    correta: R`$3$`,
    distratores: [R`$5$`, R`$7$`, R`$2$`, R`$0$`],
    resolucao: R`O cobalto neutro é $[\text{Ar}]3d^{7}4s^{2}$; o cátion $\text{Co}^{2+}$ perde os dois elétrons $4s$ e fica $[\text{Ar}]3d^{7}$. Distribuindo sete elétrons nos cinco orbitais $d$ segundo a regra de Hund, ocupa-se primeiro cada orbital com um elétron (cinco elétrons paralelos) e os dois restantes emparelham-se em dois desses orbitais. Sobram três orbitais com elétron isolado, logo três elétrons desemparelhados — a espécie é paramagnética.`,
  },
  {
    topico: T,
    subtopico: "Carga nuclear efetiva pelas regras de Slater",
    dificuldade: "dificil",
    enunciado: R`Estime a carga nuclear efetiva sentida pelo elétron $3s$ do sódio ($Z=11$), usando as regras de Slater: elétrons da camada $n-1$ blindam $0{,}85$ cada e os das camadas mais internas, $1{,}00$ cada.`,
    correta: R`$2{,}2$`,
    distratores: [R`$1{,}0$`, R`$8{,}8$`, R`$3{,}2$`, R`$11{,}0$`],
    resolucao: R`A configuração é $1s^{2}2s^{2}2p^{6}3s^{1}$. Para o elétron $3s$ não há outro elétron no mesmo grupo; os oito elétrons da camada $n=2$ contribuem com $8\times 0{,}85=6{,}8$ e os dois da camada $n=1$ com $2\times 1{,}00=2{,}0$. A constante de blindagem é $S=8{,}8$ e $Z_{\text{ef}}=11-8{,}8=2{,}2$. O valor muito abaixo de $Z$ mostra por que o elétron de valência do sódio é tão fracamente preso — daí a baixíssima energia de ionização do grupo 1.`,
  },
  {
    topico: T,
    subtopico: "Raio iônico em série isoeletrônica",
    dificuldade: "dificil",
    enunciado: R`Ordene em ordem crescente de raio as espécies isoeletrônicas $\text{N}^{3-}$, $\text{O}^{2-}$, $\text{F}^{-}$, $\text{Na}^{+}$ e $\text{Mg}^{2+}$.`,
    correta: R`$\text{Mg}^{2+}<\text{Na}^{+}<\text{F}^{-}<\text{O}^{2-}<\text{N}^{3-}$`,
    distratores: [
      R`$\text{N}^{3-}<\text{O}^{2-}<\text{F}^{-}<\text{Na}^{+}<\text{Mg}^{2+}$`,
      R`$\text{F}^{-}<\text{O}^{2-}<\text{N}^{3-}<\text{Na}^{+}<\text{Mg}^{2+}$`,
      R`$\text{Na}^{+}<\text{Mg}^{2+}<\text{F}^{-}<\text{N}^{3-}<\text{O}^{2-}$`,
      R`$\text{O}^{2-}<\text{N}^{3-}<\text{F}^{-}<\text{Mg}^{2+}<\text{Na}^{+}$`,
    ],
    resolucao: R`Todas as cinco espécies têm $10$ elétrons, portanto a mesma blindagem; o que muda é a carga nuclear: $7$, $8$, $9$, $11$ e $12$. Quanto maior $Z$, mais fortemente a mesma nuvem de dez elétrons é puxada e menor o raio. Assim o $\text{Mg}^{2+}$ ($Z=12$) é o menor e o $\text{N}^{3-}$ ($Z=7$) é o maior. Em série isoeletrônica o raio decresce monotonicamente com o número atômico, e não com a carga do íon tomada isoladamente.`,
  },
  {
    topico: T,
    subtopico: "Salto entre energias de ionização sucessivas",
    dificuldade: "dificil",
    enunciado: R`Entre os elementos $\text{Na}$, $\text{Mg}$, $\text{Al}$, $\text{Si}$ e $\text{P}$, qual apresenta a maior razão entre a segunda e a primeira energias de ionização?`,
    correta: R`$\text{Na}$`,
    distratores: [R`$\text{Mg}$`, R`$\text{Al}$`, R`$\text{Si}$`, R`$\text{P}$`],
    resolucao: R`A primeira ionização do sódio retira seu único elétron de valência, deixando o íon $\text{Na}^{+}$ com a configuração estável do neônio. A segunda ionização teria de romper esse cerne de gás nobre, o que custa quase dez vezes mais. Nos demais elementos a segunda remoção ainda ocorre na camada de valência e o salto é modesto. O padrão é geral: o pulo abrupto acontece sempre logo depois de esvaziada a camada de valência, e serve para identificar o grupo do elemento.`,
  },
  {
    topico: T,
    subtopico: "Identificação de grupo por energias de ionização",
    dificuldade: "dificil",
    enunciado: R`Um elemento do terceiro período apresenta energias de ionização sucessivas, em kJ/mol, iguais a $738$, $1451$, $7733$, $10\,540$ e $13\,630$. Determine o grupo a que ele pertence na tabela periódica.`,
    correta: R`grupo $2$`,
    distratores: [R`grupo $1$`, R`grupo $13$`, R`grupo $14$`, R`grupo $15$`],
    resolucao: R`A sequência cresce suavemente de $738$ para $1451$ e então salta mais de cinco vezes, para $7733$. Isso indica que os dois primeiros elétrons pertencem à camada de valência e o terceiro já vem do cerne de gás nobre. Um elemento com exatamente dois elétrons de valência está no grupo $2$ — trata-se do magnésio. Se fosse do grupo $13$, o salto apareceria entre a terceira e a quarta ionizações.`,
  },
  {
    topico: T,
    subtopico: "Anomalia da afinidade eletrônica do flúor",
    dificuldade: "dificil",
    enunciado: R`A afinidade eletrônica do cloro ($-349$ kJ/mol) é mais negativa que a do flúor ($-328$ kJ/mol), contrariando a tendência de grupo. A explicação aceita é:`,
    correta: R`forte repulsão no pequeno orbital $2p$`,
    distratores: [
      R`maior eletronegatividade do cloro`,
      R`menor carga nuclear efetiva do cloro`,
      R`maior energia de ligação do $\text{F}_2$`,
      R`ausência de orbitais $d$ no flúor`,
    ],
    resolucao: R`O átomo de flúor é muito pequeno, e seus sete elétrons de valência já se amontoam num orbital $2p$ compacto. O elétron adicional entra nessa mesma região e sofre repulsão intereletrônica intensa, que cancela parte da estabilização obtida. No cloro, os orbitais $3p$ são mais difusos, a densidade eletrônica se acomoda melhor e o ganho líquido é maior. O mesmo efeito faz o oxigênio ter afinidade menos negativa que o enxofre — e não tem relação com a eletronegatividade, em que o flúor lidera.`,
  },
  {
    topico: T,
    subtopico: "Contração lantanídica",
    dificuldade: "dificil",
    enunciado: R`O zircônio ($Z=40$) e o háfnio ($Z=72$) têm raios atômicos praticamente iguais, apesar de o háfnio estar um período abaixo. Esse fato é atribuído:`,
    correta: R`à blindagem ineficiente dos orbitais $4f$`,
    distratores: [
      R`à contração dos orbitais $6s$ por efeito relativístico exclusivo`,
      R`ao maior número de elétrons desemparelhados do háfnio`,
      R`à ausência de elétrons $d$ no háfnio`,
      R`à repulsão entre os elétrons de valência do zircônio`,
    ],
    resolucao: R`Entre o lantânio e o háfnio intercalam-se os catorze lantanídeos, que acrescentam catorze prótons ao núcleo e catorze elétrons a orbitais $4f$. Como os orbitais $f$ são muito difusos e pouco penetrantes, blindam mal a carga nuclear: o aumento de $Z_{\text{ef}}$ sentido pelos elétrons externos comprime o átomo e cancela o aumento de raio esperado pela mudança de período. Em consequência, zircônio e háfnio têm química tão parecida que sua separação industrial é notoriamente difícil.`,
  },
  {
    topico: T,
    subtopico: "Caráter metálico ao longo de um período",
    dificuldade: "medio",
    enunciado: R`Ao percorrer o terceiro período do sódio ao cloro, observa-se que o caráter metálico dos elementos e o caráter básico de seus óxidos:`,
    correta: R`ambos diminuem`,
    distratores: [
      R`ambos aumentam`,
      R`ambos se mantêm`,
      R`só o metálico aumenta`,
      R`só o básico aumenta`,
    ],
    resolucao: R`Da esquerda para a direita a carga nuclear efetiva cresce e o raio diminui, de modo que os elétrons de valência ficam cada vez mais presos: a tendência de ceder elétrons — a essência do caráter metálico — cai. Os óxidos acompanham: $\text{Na}_2\text{O}$ e $\text{MgO}$ são nitidamente básicos, $\text{Al}_2\text{O}_3$ é anfótero e $\text{SO}_3$ e $\text{Cl}_2\text{O}_7$ reagem com água formando ácidos fortes. As duas propriedades caminham juntas porque têm a mesma origem eletrônica.`,
  },
  {
    topico: T,
    subtopico: "Reatividade dos metais alcalinos",
    dificuldade: "medio",
    enunciado: R`A reação dos metais alcalinos com água torna-se progressivamente mais violenta de lítio para césio. A razão dessa tendência é:`,
    correta: R`a queda da primeira energia de ionização`,
    distratores: [
      R`o aumento da eletronegatividade`,
      R`o aumento da carga nuclear efetiva`,
      R`a diminuição do raio atômico`,
      R`o aumento da afinidade eletrônica`,
    ],
    resolucao: R`Descendo o grupo $1$, o elétron de valência ocupa camadas cada vez mais externas e é blindado por um número crescente de elétrons internos, o que reduz a energia necessária para arrancá-lo. Como a etapa determinante da reação é justamente a oxidação do metal, $\text{M}\rightarrow\text{M}^{+}+e^{-}$, a reação com água fica mais fácil e mais exotérmica. Raio atômico e eletronegatividade variam no sentido oposto ao afirmado nos distratores.`,
  },
  {
    topico: T,
    subtopico: "Poder oxidante dos halogênios",
    dificuldade: "dificil",
    enunciado: R`Borbulhando $\text{Cl}_2$ numa solução de $\text{KBr}$ observa-se o aparecimento de uma coloração alaranjada, mas nada acontece ao borbulhar $\text{Br}_2$ numa solução de $\text{KCl}$. Esse par de observações mostra que:`,
    correta: R`o cloro é o oxidante mais forte`,
    distratores: [
      R`o brometo é o redutor mais fraco`,
      R`o brometo é o oxidante mais forte`,
      R`o cloreto é o redutor mais forte`,
      R`os dois halogênios têm poder oxidante igual`,
    ],
    resolucao: R`A cor alaranjada denuncia a formação de $\text{Br}_2$: o cloro arrancou elétrons do brometo, $\text{Cl}_2+2\text{Br}^{-}\rightarrow 2\text{Cl}^{-}+\text{Br}_2$. Como a reação inversa não acontece, o cloro tem maior tendência a se reduzir, isto é, é o oxidante mais forte. Isso reflete a diminuição do poder oxidante ao descer o grupo $17$, acompanhando a queda da afinidade eletrônica efetiva e o aumento do raio — o flúor é o extremo superior dessa escala.`,
  },
  {
    topico: T,
    subtopico: "Reatividade dos gases nobres",
    dificuldade: "dificil",
    enunciado: R`Compostos como $\text{XeF}_4$ são conhecidos desde 1962, mas não existem compostos análogos de hélio ou neônio. A explicação está em que, no xenônio:`,
    correta: R`a energia de ionização é bem menor`,
    distratores: [
      R`a camada de valência está incompleta`,
      R`a afinidade eletrônica é muito negativa`,
      R`a eletronegatividade é maior`,
      R`o raio atômico é menor`,
    ],
    resolucao: R`Todos os gases nobres têm a camada de valência completa, mas o xenônio é grande e seus elétrons $5p$ estão longe do núcleo e bem blindados: sua primeira energia de ionização ($1170$ kJ/mol) é comparável à do oxigênio, baixa o bastante para que oxidantes muito agressivos como o flúor consigam formar ligações reais com ele. Hélio e neônio, minúsculos, têm energias de ionização de $2372$ e $2081$ kJ/mol, inatingíveis por qualquer reagente químico.`,
  },
  {
    topico: T,
    subtopico: "Ponto de fusão ao longo do terceiro período",
    dificuldade: "dificil",
    enunciado: R`No terceiro período, o silício apresenta ponto de fusão muito superior ao do sódio, do fósforo e do enxofre. A causa desse máximo é:`,
    correta: R`a rede covalente tridimensional`,
    distratores: [
      R`a ligação metálica mais forte do período`,
      R`a alta polaridade das ligações $\text{Si}-\text{Si}$`,
      R`as ligações de hidrogênio entre as moléculas`,
      R`a maior massa molar entre os cinco elementos`,
    ],
    resolucao: R`No silício cada átomo se liga covalentemente a outros quatro num arranjo tetraédrico que se estende por todo o cristal, como no diamante. Fundir esse sólido significa romper ligações covalentes, o que exige temperaturas altíssimas. O sódio é um metal de ligação relativamente fraca, e fósforo e enxofre formam sólidos moleculares ($\text{P}_4$ e $\text{S}_8$) mantidos apenas por forças de dispersão. Ligação $\text{Si}-\text{Si}$ é apolar, e não há hidrogênio envolvido.`,
  },
  {
    topico: T,
    subtopico: "Contagem de partículas subatômicas em amostra macroscópica",
    dificuldade: "dificil",
    enunciado: R`Determine o número de nêutrons contidos em $0{,}50$ mol do isótopo $^{13}\text{C}$. Use $N_A=6{,}02\times 10^{23}$ mol$^{-1}$.`,
    correta: R`$2{,}1\times 10^{24}$`,
    distratores: [
      R`$3{,}0\times 10^{24}$`,
      R`$1{,}8\times 10^{24}$`,
      R`$4{,}2\times 10^{24}$`,
      R`$2{,}1\times 10^{23}$`,
    ],
    resolucao: R`O carbono tem $Z=6$, logo o isótopo de número de massa $13$ possui $13-6=7$ nêutrons por átomo. Em $0{,}50$ mol há $0{,}50\times 6{,}02\times 10^{23}=3{,}01\times 10^{23}$ átomos. Multiplicando, $3{,}01\times 10^{23}\times 7\approx 2{,}1\times 10^{24}$ nêutrons. O erro mais comum é usar $13$ (número de massa) em vez de $7$, o que daria $3{,}9\times 10^{24}$, ou esquecer o fator $0{,}50$.`,
  },
  {
    topico: T,
    subtopico: "Energia de radiação por mol de fótons",
    dificuldade: "dificil",
    enunciado: R`Lâmpadas germicidas emitem radiação ultravioleta de $254$ nm. Calcule a energia correspondente a um mol desses fótons, usando $\lambda(\text{nm})=\dfrac{1240}{E(\text{eV})}$ e $1$ eV $=96{,}5$ kJ/mol.`,
    correta: R`$471$ kJ/mol`,
    distratores: [R`$236$ kJ/mol`, R`$942$ kJ/mol`, R`$302$ kJ/mol`, R`$118$ kJ/mol`],
    resolucao: R`A energia de cada fóton é $E=\dfrac{1240}{254}=4{,}88$ eV. Convertendo para base molar, $4{,}88\times 96{,}5\approx 471$ kJ/mol. Esse valor supera a energia típica de uma ligação $\text{C}-\text{C}$ ($348$ kJ/mol) e é da ordem das ligações do esqueleto do DNA: é exatamente por isso que essa radiação danifica material genético e esteriliza superfícies, enquanto a luz visível, de alguns poucos elétron-volts a menos, não o faz.`,
  },
  {
    topico: T,
    subtopico: "Comparação de energia entre transições eletrônicas",
    dificuldade: "dificil",
    enunciado: R`No átomo de hidrogênio ($E_n=-\dfrac{13{,}6}{n^2}$ eV), qual das transições abaixo emite o fóton de maior energia?`,
    correta: R`$n=3\rightarrow n=1$`,
    distratores: [
      R`$n=2\rightarrow n=1$`,
      R`$n=4\rightarrow n=2$`,
      R`$n=3\rightarrow n=2$`,
      R`$n=5\rightarrow n=4$`,
    ],
    resolucao: R`Calcule $\Delta E=13{,}6\left(\dfrac{1}{n_f^2}-\dfrac{1}{n_i^2}\right)$ em cada caso: $3\to1$ dá $13{,}6\left(1-\tfrac19\right)=12{,}09$ eV; $2\to1$ dá $10{,}2$ eV; $4\to2$ dá $2{,}55$ eV; $3\to2$ dá $1{,}89$ eV; $5\to4$ dá $0{,}31$ eV. Vence a transição $3\to1$. Repare que o tamanho do salto em $n$ não decide nada — o que importa é a proximidade do nível final ao fundamental, onde os níveis estão muito mais espaçados.`,
  },
  {
    topico: T,
    subtopico: "Espectro de emissão de íon hidrogenoide",
    dificuldade: "dificil",
    enunciado: R`Determine o comprimento de onda do fóton emitido na transição $n=2\rightarrow n=1$ do íon $\text{He}^{+}$, para o qual $E_n=-13{,}6\,\dfrac{Z^2}{n^2}$ eV. Use $\lambda(\text{nm})=\dfrac{1240}{E(\text{eV})}$.`,
    correta: R`$30{,}4$ nm`,
    distratores: [R`$121{,}6$ nm`, R`$60{,}8$ nm`, R`$15{,}2$ nm`, R`$91{,}2$ nm`],
    resolucao: R`Com $Z=2$, $\Delta E=13{,}6\cdot 4\left(1-\dfrac{1}{4}\right)=54{,}4\times 0{,}75=40{,}8$ eV. Logo $\lambda=\dfrac{1240}{40{,}8}\approx 30{,}4$ nm. Como a energia escala com $Z^2$, o comprimento de onda encolhe pelo fator $Z^2=4$ em relação à linha correspondente do hidrogênio ($121{,}6$ nm, a primeira da série de Lyman). Responder $60{,}8$ nm corresponde a escalar apenas com $Z$.`,
  },
  {
    topico: T,
    subtopico: "Regra de Hund e princípio da exclusão",
    dificuldade: "medio",
    enunciado: R`Um estudante distribui os três elétrons $2p$ do nitrogênio colocando dois deles emparelhados num mesmo orbital e o terceiro sozinho em outro. Essa distribuição:`,
    correta: R`viola a regra de Hund`,
    distratores: [
      R`viola o princípio da exclusão de Pauli`,
      R`viola o princípio da incerteza`,
      R`está correta para o estado fundamental`,
      R`viola o princípio de Aufbau`,
    ],
    resolucao: R`O princípio de Pauli está respeitado, pois os dois elétrons emparelhados teriam spins opostos. O que falha é a regra de Hund: havendo orbitais degenerados disponíveis, o estado de menor energia é aquele com o maior número de spins paralelos em orbitais diferentes, porque elétrons em orbitais distintos se repelem menos. A configuração descrita corresponde, portanto, a um estado excitado; o estado fundamental do nitrogênio tem três elétrons desemparelhados.`,
  },
  {
    topico: T,
    subtopico: "Degenerescência de orbitais",
    dificuldade: "dificil",
    enunciado: R`Comparando o átomo de hidrogênio com o de lítio, a afirmação correta sobre as energias dos orbitais $2s$ e $2p$ é:`,
    correta: R`são iguais no $\text{H}$ e diferentes no $\text{Li}$`,
    distratores: [
      R`são diferentes no $\text{H}$ e iguais no $\text{Li}$`,
      R`são iguais nos dois átomos`,
      R`são diferentes nos dois átomos`,
      R`o $2p$ é o mais estável nos dois átomos`,
    ],
    resolucao: R`No hidrogênio existe um único elétron e nenhuma repulsão intereletrônica: a energia depende exclusivamente de $n$, de modo que $2s$ e $2p$ são degenerados. No lítio há elétrons $1s$ que blindam o núcleo, e a blindagem é sentida de modo diferente por orbitais de penetração diferente. O $2s$, mais penetrante, experimenta maior $Z_{\text{ef}}$ e fica abaixo do $2p$ — razão pela qual o terceiro elétron do lítio ocupa o $2s$.`,
  },
  {
    topico: T,
    subtopico: "Anomalia de raio no bloco p",
    dificuldade: "dificil",
    enunciado: R`Os raios atômicos do alumínio ($143$ pm) e do gálio ($135$ pm) contrariam a expectativa de aumento ao descer o grupo $13$. Esse comportamento decorre:`,
    correta: R`do preenchimento dos orbitais $3d$`,
    distratores: [
      R`do preenchimento dos orbitais $4f$`,
      R`da maior eletronegatividade do gálio`,
      R`do menor número de camadas do gálio`,
      R`da hibridização dos orbitais de valência`,
    ],
    resolucao: R`Entre o alumínio e o gálio intercala-se a primeira série de transição, que acrescenta dez prótons e dez elétrons $3d$. Os orbitais $d$ blindam mal, e a carga nuclear efetiva sentida pelos elétrons $4p$ do gálio acaba maior que a sentida pelos $3p$ do alumínio, comprimindo o átomo o suficiente para anular o ganho do período adicional. É o análogo, no bloco $p$, da contração lantanídica que aproxima zircônio e háfnio.`,
  },
  {
    topico: T,
    subtopico: "Exceção de energia de ionização entre grupos 15 e 16",
    dificuldade: "dificil",
    enunciado: R`A primeira energia de ionização do enxofre ($1000$ kJ/mol) é menor que a do fósforo ($1012$ kJ/mol), invertendo a tendência do período. A causa é:`,
    correta: R`a repulsão no orbital $3p$ duplamente ocupado`,
    distratores: [
      R`a maior carga nuclear efetiva do fósforo`,
      R`o menor raio atômico do enxofre`,
      R`a maior afinidade eletrônica do fósforo`,
      R`a maior blindagem exercida pelos orbitais $3d$`,
    ],
    resolucao: R`O fósforo tem configuração $[\text{Ne}]3s^{2}3p^{3}$, com os três orbitais $p$ semipreenchidos e nenhum par. No enxofre, $[\text{Ne}]3s^{2}3p^{4}$, o quarto elétron é obrigado a emparelhar-se, e a repulsão entre dois elétrons no mesmo orbital eleva sua energia. Arrancá-lo custa, portanto, um pouco menos, apesar da carga nuclear maior. A mesma inversão aparece entre nitrogênio e oxigênio, e entre berílio e boro por motivo análogo (mudança de subnível).`,
  },
  {
    topico: T,
    subtopico: "Espectro de linhas e quantização",
    dificuldade: "medio",
    enunciado: R`A lâmpada de vapor de sódio emite um espectro formado por linhas estreitas e bem definidas, e não por um contínuo de cores. Essa observação evidencia que:`,
    correta: R`as energias eletrônicas são quantizadas`,
    distratores: [
      R`os elétrons giram em órbitas circulares`,
      R`os fótons têm massa de repouso nula`,
      R`o sódio possui um só elétron de valência`,
      R`a temperatura do gás é muito elevada`,
    ],
    resolucao: R`Cada linha corresponde a fótons de uma única energia, $\Delta E=h\nu$, emitidos quando o elétron passa de um estado permitido para outro. Se as energias eletrônicas pudessem assumir qualquer valor, as transições cobririam todas as energias e o espectro seria contínuo, como o de um sólido incandescente. O fato de o sódio ter um elétron de valência explica a simplicidade do espectro, mas não a sua natureza discreta.`,
  },
  {
    topico: T,
    subtopico: "Comparação entre raio atômico e raio iônico",
    dificuldade: "medio",
    enunciado: R`O raio do íon $\text{Cl}^{-}$ ($181$ pm) é bem maior que o do átomo de cloro ($99$ pm). A explicação correta é:`,
    correta: R`a repulsão cresce com o mesmo número de prótons`,
    distratores: [
      R`o número de camadas aumenta em uma unidade`,
      R`a carga nuclear efetiva aumenta no ânion`,
      R`o número de prótons diminui no ânion`,
      R`a blindagem dos elétrons internos diminui`,
    ],
    resolucao: R`O ânion tem um elétron a mais, mas exatamente os mesmos $17$ prótons. A carga nuclear disponível passa a ser repartida entre $18$ elétrons, de modo que a atração por elétron cai e a repulsão intereletrônica na camada de valência cresce: a nuvem se expande. Nenhuma camada nova é aberta — o elétron extra entra no próprio subnível $3p$. Pelo raciocínio inverso, cátions são sempre menores que os átomos que os originam.`,
  },
  {
    topico: T,
    subtopico: "Composição de um íon a partir do símbolo nuclear",
    dificuldade: "medio",
    enunciado: R`Determine, nessa ordem, o número de prótons, nêutrons e elétrons do íon $^{56}_{26}\text{Fe}^{3+}$.`,
    correta: R`$26$, $30$ e $23$`,
    distratores: [
      R`$26$, $30$ e $26$`,
      R`$26$, $26$ e $23$`,
      R`$23$, $30$ e $26$`,
      R`$26$, $56$ e $29$`,
    ],
    resolucao: R`O número atômico dá diretamente os prótons: $26$. Os nêutrons são a diferença entre o número de massa e o atômico: $56-26=30$. A carga $3+$ significa três elétrons a menos que o átomo neutro: $26-3=23$. Vale lembrar que número de massa e carga são informações independentes — a carga nunca altera a contagem de prótons ou nêutrons, apenas a de elétrons.`,
  },
  {
    topico: T,
    subtopico: "Eletronegatividade e tendência periódica",
    dificuldade: "medio",
    enunciado: R`Entre os elementos $\text{B}$, $\text{N}$, $\text{O}$, $\text{Al}$ e $\text{S}$, qual apresenta a maior eletronegatividade de Pauling?`,
    correta: R`$\text{O}$`,
    distratores: [R`$\text{N}$`, R`$\text{S}$`, R`$\text{B}$`, R`$\text{Al}$`],
    resolucao: R`A eletronegatividade cresce ao longo do período (maior $Z_{\text{ef}}$, menor raio) e decresce ao descer o grupo. Entre os citados, o oxigênio combina alta posição no período com o segundo período, e só perde para o flúor em toda a tabela: seu valor é $3{,}5$, contra $3{,}0$ do nitrogênio, $2{,}5$ do enxofre, $2{,}0$ do boro e $1{,}5$ do alumínio. A comparação $\text{N}$ contra $\text{S}$ mostra que período e grupo às vezes competem — aqui prevalece o período.`,
  },
  {
    topico: T,
    subtopico: "Densidade de probabilidade radial",
    dificuldade: "dificil",
    enunciado: R`No átomo de hidrogênio, a função de distribuição radial do orbital $1s$ tem máximo em $52{,}9$ pm, embora a densidade de probabilidade $\left|\psi\right|^{2}$ seja máxima no próprio núcleo. A conciliação entre os dois fatos está em que:`,
    correta: R`o volume da casca esférica cresce com a distância`,
    distratores: [
      R`a função de onda muda de sinal em $52{,}9$ pm`,
      R`existe um nó radial nessa distância`,
      R`o elétron não pode ocupar o núcleo`,
      R`a energia potencial é mínima nessa distância`,
    ],
    resolucao: R`A função de distribuição radial é $4\pi r^{2}\left|\psi\right|^{2}$: ela mede a probabilidade de encontrar o elétron numa casca fina de raio $r$, e não num ponto. Perto do núcleo $\left|\psi\right|^{2}$ é grande, mas o volume disponível tende a zero; longe, o volume é grande, mas $\left|\psi\right|^{2}$ decai exponencialmente. O produto tem máximo intermediário, justamente no raio de Bohr. O orbital $1s$ não tem nó algum, o que descarta duas das alternativas.`,
  },
];
