// Lote 3 de Química Geral — Tópico 4: Funções Inorgânicas e Reações Químicas.
// Estilo Brown, "Química: A Ciência Central" (caps. 2, 3, 4, 10 e 13):
// nomenclatura, funções inorgânicas, reações em solução aquosa, redox,
// estequiometria, soluções e gases. Sem questões `facil`.
const R = String.raw;
const T = "Funções Inorgânicas e Reações Químicas";

export const questoes = [
  {
    topico: T,
    subtopico: "Nomenclatura de oxiácidos",
    dificuldade: "medio",
    enunciado: R`Qual é o nome do ácido de fórmula $\text{HClO}_2$?`,
    correta: R`ácido cloroso`,
    distratores: [R`ácido hipocloroso`, R`ácido clórico`, R`ácido perclórico`, R`ácido clorídrico`],
    resolucao: R`A família dos oxiácidos do cloro tem quatro membros, nomeados pelo número de oxigênios: $\text{HClO}$ é o hipocloroso, $\text{HClO}_2$ o cloroso, $\text{HClO}_3$ o clórico e $\text{HClO}_4$ o perclórico. A regra geral parte do ácido padrão terminado em "-ico"; um oxigênio a menos troca o sufixo para "-oso", dois a menos acrescenta o prefixo "hipo-" e um a mais, "per-". O ácido clorídrico, $\text{HCl}$, é um hidrácido e não pertence a essa série.`,
  },
  {
    topico: T,
    subtopico: "Fórmula a partir do nome de sal",
    dificuldade: "medio",
    enunciado: R`Escreva a fórmula do sulfato de alumínio, usado como coagulante no tratamento de água.`,
    correta: R`$\text{Al}_2(\text{SO}_4)_3$`,
    distratores: [
      R`$\text{AlSO}_4$`,
      R`$\text{Al}_3(\text{SO}_4)_2$`,
      R`$\text{Al}(\text{SO}_4)_3$`,
      R`$\text{Al}_2\text{SO}_4$`,
    ],
    resolucao: R`O alumínio forma cátion $\text{Al}^{3+}$ e o sulfato é $\text{SO}_4^{2-}$. Para que o composto seja eletricamente neutro, a carga total positiva deve igualar a negativa: são necessários dois alumínios ($+6$) e três sulfatos ($-6$), o que dá $\text{Al}_2(\text{SO}_4)_3$. O atalho prático é trocar os módulos das cargas entre os índices, sempre simplificando a razão quando possível — o que aqui não ocorre, pois $2$ e $3$ são primos entre si.`,
  },
  {
    topico: T,
    subtopico: "Nomenclatura de metais com Nox variável",
    dificuldade: "medio",
    enunciado: R`Qual é o nome do composto $\text{FeCl}_3$ na nomenclatura de estoque?`,
    correta: R`cloreto de ferro (III)`,
    distratores: [
      R`cloreto de ferro (II)`,
      R`tricloreto de ferro (II)`,
      R`clorato de ferro (III)`,
      R`cloreto férrico (II)`,
    ],
    resolucao: R`O cloreto tem carga $1-$; três deles exigem um cátion $3+$, de modo que o número de oxidação do ferro é $+3$, indicado em algarismos romanos entre parênteses. A nomenclatura tradicional usaria o sufixo "-ico" para o maior Nox — cloreto férrico — e "-oso" para o menor, $\text{FeCl}_2$, cloreto ferroso. Já o clorato seria o oxiânion $\text{ClO}_3^{-}$, que não aparece aqui.`,
  },
  {
    topico: T,
    subtopico: "Óxidos anfóteros",
    dificuldade: "medio",
    enunciado: R`Qual dos óxidos abaixo reage tanto com ácidos fortes quanto com bases fortes?`,
    correta: R`$\text{Al}_2\text{O}_3$`,
    distratores: [
      R`$\text{Na}_2\text{O}$`,
      R`$\text{P}_4\text{O}_{10}$`,
      R`$\text{Cl}_2\text{O}_7$`,
      R`$\text{Li}_2\text{O}$`,
    ],
    resolucao: R`O óxido de alumínio é anfótero: com ácido comporta-se como base, formando $\text{Al}^{3+}$, e com base forte comporta-se como ácido, formando o íon aluminato $\text{Al}(\text{OH})_4^{-}$. Esse caráter duplo é típico de elementos na fronteira entre metais e ametais, como $\text{Al}$, $\text{Zn}$, $\text{Pb}$ e $\text{Sn}$. $\text{Na}_2\text{O}$ e $\text{Li}_2\text{O}$ são francamente básicos, enquanto $\text{P}_4\text{O}_{10}$ e $\text{Cl}_2\text{O}_7$ são óxidos ácidos, que em água dão ácido fosfórico e ácido perclórico.`,
  },
  {
    topico: T,
    subtopico: "Óxidos ácidos e chuva ácida",
    dificuldade: "medio",
    enunciado: R`A queima de combustíveis com enxofre libera $\text{SO}_2$, que se oxida na atmosfera a $\text{SO}_3$. Qual espécie se forma quando esse $\text{SO}_3$ encontra a água das nuvens?`,
    correta: R`$\text{H}_2\text{SO}_4$`,
    distratores: [R`$\text{H}_2\text{SO}_3$`, R`$\text{H}_2\text{S}$`, R`$\text{S}_2\text{O}_3^{2-}$`, R`$\text{HSO}_3^{-}$`],
    resolucao: R`Óxidos ácidos reagem com água produzindo o ácido de mesmo número de oxidação do elemento central. No $\text{SO}_3$ o enxofre está $+6$, e o ácido correspondente é o sulfúrico: $\text{SO}_3+\text{H}_2\text{O}\rightarrow\text{H}_2\text{SO}_4$. O $\text{SO}_2$, com enxofre $+4$, daria ácido sulfuroso. Como o sulfúrico é um ácido forte e diprótico, é ele o principal responsável pela acidez extrema da chuva em regiões industriais.`,
  },
  {
    topico: T,
    subtopico: "Pares conjugados de Brønsted-Lowry",
    dificuldade: "dificil",
    enunciado: R`No equilíbrio $\text{HCO}_3^{-}+\text{H}_2\text{O}\rightleftharpoons\text{H}_2\text{CO}_3+\text{OH}^{-}$, identifique o ácido conjugado do $\text{HCO}_3^{-}$.`,
    correta: R`$\text{H}_2\text{CO}_3$`,
    distratores: [R`$\text{H}_2\text{O}$`, R`$\text{OH}^{-}$`, R`$\text{CO}_3^{2-}$`, R`$\text{HCO}_3^{-}$`],
    resolucao: R`Um par conjugado difere por exatamente um próton. Nesse equilíbrio o bicarbonato atua como base de Brønsted, recebendo $\text{H}^{+}$ da água e transformando-se em $\text{H}_2\text{CO}_3$ — seu ácido conjugado. A água atua como ácido e seu par conjugado é o $\text{OH}^{-}$. Note que o $\text{CO}_3^{2-}$ é a base conjugada do bicarbonato, e não seu ácido: é a espécie que resultaria da perda de um próton.`,
  },
  {
    topico: T,
    subtopico: "Força relativa de oxiácidos",
    dificuldade: "dificil",
    enunciado: R`Ordene em ordem crescente de força ácida os compostos $\text{HClO}$, $\text{HClO}_2$ e $\text{HClO}_3$.`,
    correta: R`$\text{HClO}<\text{HClO}_2<\text{HClO}_3$`,
    distratores: [
      R`$\text{HClO}_3<\text{HClO}_2<\text{HClO}$`,
      R`$\text{HClO}_2<\text{HClO}<\text{HClO}_3$`,
      R`$\text{HClO}<\text{HClO}_3<\text{HClO}_2$`,
      R`$\text{HClO}_3<\text{HClO}<\text{HClO}_2$`,
    ],
    resolucao: R`Em oxiácidos de um mesmo elemento central, a força cresce com o número de oxigênios não protonados. Cada oxigênio adicional retira densidade eletrônica do cloro por efeito indutivo, o que enfraquece a ligação $\text{O}-\text{H}$ e, sobretudo, dispersa a carga negativa do ânion resultante por mais átomos, estabilizando a base conjugada. Quanto mais estável a base conjugada, mais forte o ácido: o $\text{HClO}_4$, com quatro oxigênios, é um dos ácidos mais fortes conhecidos.`,
  },
  {
    topico: T,
    subtopico: "Hidrólise de sais e caráter do meio",
    dificuldade: "dificil",
    enunciado: R`Qual dos sais abaixo, dissolvido em água pura, produz solução de pH maior que $7$?`,
    correta: R`$\text{CH}_3\text{COONa}$`,
    distratores: [R`$\text{NH}_4\text{Cl}$`, R`$\text{NaCl}$`, R`$\text{KNO}_3$`, R`$\text{NH}_4\text{NO}_3$`],
    resolucao: R`O caráter da solução vem da força dos "pais" do sal. O acetato de sódio provém de base forte ($\text{NaOH}$) e ácido fraco ($\text{CH}_3\text{COOH}$): o ânion acetato hidrolisa, retirando prótons da água e liberando $\text{OH}^{-}$, e o meio fica básico. $\text{NH}_4\text{Cl}$ e $\text{NH}_4\text{NO}_3$ vêm de base fraca e ácido forte, com o cátion amônio cedendo prótons e acidificando o meio. $\text{NaCl}$ e $\text{KNO}_3$, de ácido e base fortes, não hidrolisam e permanecem neutros.`,
  },
  {
    topico: T,
    subtopico: "Espécies anfipróticas",
    dificuldade: "medio",
    enunciado: R`Qual das espécies abaixo pode atuar tanto como ácido quanto como base de Brønsted-Lowry?`,
    correta: R`$\text{HCO}_3^{-}$`,
    distratores: [R`$\text{CO}_3^{2-}$`, R`$\text{NH}_4^{+}$`, R`$\text{Cl}^{-}$`, R`$\text{CH}_3\text{COOH}$`],
    resolucao: R`Para ser anfiprótica, a espécie precisa ter um próton ionizável e, ao mesmo tempo, um par isolado capaz de receber outro. O bicarbonato satisfaz as duas condições: perde $\text{H}^{+}$ formando $\text{CO}_3^{2-}$ ou o recebe formando $\text{H}_2\text{CO}_3$. O carbonato só pode receber, o amônio e o ácido acético só podem ceder, e o cloreto é base conjugada de ácido forte, tão fraca que não reage apreciavelmente. Esse comportamento duplo é a base do tampão bicarbonato que controla o pH do sangue.`,
  },
  {
    topico: T,
    subtopico: "Equação iônica líquida de precipitação",
    dificuldade: "medio",
    enunciado: R`Escreva a equação iônica líquida da reação entre soluções aquosas de $\text{AgNO}_3$ e $\text{NaCl}$.`,
    correta: R`$\text{Ag}^{+}+\text{Cl}^{-}\rightarrow\text{AgCl}(s)$`,
    distratores: [
      R`$\text{Ag}^{+}+\text{NO}_3^{-}\rightarrow\text{AgNO}_3(s)$`,
      R`$\text{Na}^{+}+\text{Cl}^{-}\rightarrow\text{NaCl}(s)$`,
      R`$\text{Na}^{+}+\text{NO}_3^{-}\rightarrow\text{NaNO}_3(s)$`,
      R`$\text{AgNO}_3+\text{NaCl}\rightarrow\text{AgCl}+\text{NaNO}_3$`,
    ],
    resolucao: R`Todos os reagentes estão dissociados em solução, e o único produto insolúvel é o cloreto de prata. Os íons $\text{Na}^{+}$ e $\text{NO}_3^{-}$ aparecem inalterados dos dois lados da equação completa e são espectadores: devem ser cancelados. Sobra apenas $\text{Ag}^{+}+\text{Cl}^{-}\rightarrow\text{AgCl}(s)$. A última alternativa é a equação molecular, correta mas não iônica líquida, porque ainda escreve os espectadores.`,
  },
  {
    topico: T,
    subtopico: "Regras de solubilidade",
    dificuldade: "dificil",
    enunciado: R`A mistura de quais soluções aquosas abaixo produz precipitado?`,
    correta: R`$\text{Pb(NO}_3)_2$ e $\text{KI}$`,
    distratores: [
      R`$\text{NaNO}_3$ e $\text{KCl}$`,
      R`$\text{CaCl}_2$ e $\text{NaNO}_3$`,
      R`$\text{K}_2\text{SO}_4$ e $\text{NaCl}$`,
      R`$\text{NH}_4\text{Cl}$ e $\text{KNO}_3$`,
    ],
    resolucao: R`As regras de solubilidade dizem que nitratos e sais de metais alcalinos e de amônio são sempre solúveis — o que já elimina toda combinação em que os produtos possíveis se encaixam nessas categorias. No primeiro caso, porém, a troca produz $\text{PbI}_2$, e os iodetos são solúveis exceto os de prata, chumbo e mercúrio. Forma-se então o precipitado amarelo característico do iodeto de chumbo, usado como demonstração clássica de dupla troca.`,
  },
  {
    topico: T,
    subtopico: "Neutralização de ácido poliprótico",
    dificuldade: "dificil",
    enunciado: R`Determine o volume de solução de $\text{NaOH}$ $0{,}50$ mol/L necessário para neutralizar completamente $25$ mL de $\text{H}_3\text{PO}_4$ $0{,}20$ mol/L.`,
    correta: R`$30$ mL`,
    distratores: [R`$10$ mL`, R`$90$ mL`, R`$15$ mL`, R`$60$ mL`],
    resolucao: R`A quantidade de ácido é $0{,}025\times 0{,}20=5{,}0\times 10^{-3}$ mol. Sendo triprótico, cada mol consome três mols de hidróxido na neutralização total: $1{,}5\times 10^{-2}$ mol de $\text{NaOH}$. O volume é $\dfrac{1{,}5\times 10^{-2}}{0{,}50}=0{,}030$ L, ou $30$ mL. Ignorar a acidez tripla levaria a $10$ mL — o volume correspondente apenas à primeira ionização.`,
  },
  {
    topico: T,
    subtopico: "Titulação e determinação de concentração",
    dificuldade: "dificil",
    enunciado: R`Na titulação de $20{,}0$ mL de solução de $\text{H}_2\text{SO}_4$, o ponto de equivalência é alcançado com $25{,}0$ mL de $\text{NaOH}$ $0{,}200$ mol/L. Determine a concentração do ácido.`,
    correta: R`$0{,}125$ mol/L`,
    distratores: [
      R`$0{,}250$ mol/L`,
      R`$0{,}0625$ mol/L`,
      R`$0{,}160$ mol/L`,
      R`$0{,}500$ mol/L`,
    ],
    resolucao: R`A base fornece $0{,}0250\times 0{,}200=5{,}00\times 10^{-3}$ mol de $\text{OH}^{-}$. Como o ácido sulfúrico é diprótico, $\text{H}_2\text{SO}_4+2\text{NaOH}\rightarrow\text{Na}_2\text{SO}_4+2\text{H}_2\text{O}$, a quantidade de ácido é a metade: $2{,}50\times 10^{-3}$ mol. A concentração vale $\dfrac{2{,}50\times 10^{-3}}{0{,}0200}=0{,}125$ mol/L. Tratar o ácido como monoprótico dobraria o resultado.`,
  },
  {
    topico: T,
    subtopico: "Balanceamento de equação redox em meio ácido",
    dificuldade: "dificil",
    enunciado: R`Na equação $\text{MnO}_4^{-}+\text{Fe}^{2+}+\text{H}^{+}\rightarrow\text{Mn}^{2+}+\text{Fe}^{3+}+\text{H}_2\text{O}$, determine o coeficiente do $\text{H}^{+}$ após o balanceamento com os menores inteiros.`,
    correta: R`$8$`,
    distratores: [R`$4$`, R`$16$`, R`$5$`, R`$2$`],
    resolucao: R`O manganês cai de $+7$ para $+2$, ganhando $5$ elétrons; o ferro sobe de $+2$ para $+3$, perdendo $1$. Para igualar os elétrons são necessários cinco ferros por permanganato: $\text{MnO}_4^{-}+5\text{Fe}^{2+}+\text{H}^{+}\rightarrow\text{Mn}^{2+}+5\text{Fe}^{3+}+\text{H}_2\text{O}$. Os quatro oxigênios do permanganato saem como quatro moléculas de água, que exigem oito hidrogênios. A conferência de cargas fecha: $-1+10+8=+17$ à esquerda e $+2+15=+17$ à direita.`,
  },
  {
    topico: T,
    subtopico: "Balanceamento de equação redox em meio básico",
    dificuldade: "dificil",
    enunciado: R`Balanceando $\text{MnO}_4^{-}+\text{I}^{-}\rightarrow\text{MnO}_2+\text{IO}_3^{-}$ em meio básico, com adição de $\text{H}_2\text{O}$ e $\text{OH}^{-}$, determine o coeficiente do íon hidróxido.`,
    correta: R`$2$`,
    distratores: [R`$1$`, R`$4$`, R`$6$`, R`$8$`],
    resolucao: R`O manganês vai de $+7$ a $+4$, ganhando $3$ elétrons; o iodo vai de $-1$ a $+5$, perdendo $6$. São necessários dois permanganatos por iodeto: $2\text{MnO}_4^{-}+\text{I}^{-}\rightarrow 2\text{MnO}_2+\text{IO}_3^{-}$. A carga à esquerda é $-3$ e à direita, $-1$; acrescentando $2\,\text{OH}^{-}$ à direita as cargas se igualam, e uma molécula de água à esquerda fecha hidrogênios e oxigênios: $2\text{MnO}_4^{-}+\text{I}^{-}+\text{H}_2\text{O}\rightarrow 2\text{MnO}_2+\text{IO}_3^{-}+2\text{OH}^{-}$.`,
  },
  {
    topico: T,
    subtopico: "Número de oxidação em íon poliatômico",
    dificuldade: "dificil",
    enunciado: R`Determine o número de oxidação médio do enxofre no íon tiossulfato, $\text{S}_2\text{O}_3^{2-}$.`,
    correta: R`$+2$`,
    distratores: [R`$+4$`, R`$+6$`, R`$-2$`, R`$+3$`],
    resolucao: R`Atribuindo $-2$ a cada oxigênio, a soma dos números de oxidação deve igualar a carga do íon: $2x+3(-2)=-2$, logo $2x=+4$ e $x=+2$. Trata-se de um valor médio: na estrutura real os dois enxofres são quimicamente distintos, um central com Nox $+5$ e um terminal com $-1$. A média é suficiente para balancear equações, mas convém lembrar que ela nem sempre corresponde ao estado de um átomo individual.`,
  },
  {
    topico: T,
    subtopico: "Identificação de agente oxidante",
    dificuldade: "medio",
    enunciado: R`Na reação $\text{Zn}(s)+2\text{HCl}(aq)\rightarrow\text{ZnCl}_2(aq)+\text{H}_2(g)$, qual espécie atua como agente oxidante?`,
    correta: R`$\text{H}^{+}$`,
    distratores: [R`$\text{Zn}$`, R`$\text{Cl}^{-}$`, R`$\text{ZnCl}_2$`, R`$\text{H}_2$`],
    resolucao: R`O zinco passa de $0$ a $+2$: perde elétrons, oxida-se e portanto é o agente redutor. O hidrogênio passa de $+1$ a $0$: recebe elétrons, reduz-se e é o agente oxidante. O cloreto mantém o número de oxidação $-1$ dos dois lados e é apenas espectador. A confusão frequente vem do nome: o agente oxidante é quem provoca a oxidação alheia e, ao fazê-lo, é reduzido.`,
  },
  {
    topico: T,
    subtopico: "Série de reatividade dos metais",
    dificuldade: "dificil",
    enunciado: R`Uma lâmina de zinco mergulhada em $\text{CuSO}_4$ escurece e a solução azul desbota; uma lâmina de cobre em $\text{ZnSO}_4$ permanece inalterada. Conclui-se que:`,
    correta: R`o zinco é mais facilmente oxidado que o cobre`,
    distratores: [
      R`o cobre é mais facilmente oxidado que o zinco`,
      R`os dois metais têm a mesma tendência a oxidar`,
      R`o sulfato participa da transferência de elétrons`,
      R`o cobre reduz o zinco metálico na segunda experiência`,
    ],
    resolucao: R`A primeira experiência mostra a reação $\text{Zn}+\text{Cu}^{2+}\rightarrow\text{Zn}^{2+}+\text{Cu}$: o zinco cede elétrons ao íon cobre, que se deposita como metal avermelhado. A ausência de reação no sentido inverso indica que o cobre não consegue reduzir o $\text{Zn}^{2+}$. Em termos de potenciais padrão, $E^{\circ}\left(\text{Zn}^{2+}/\text{Zn}\right)=-0{,}76$ V é menor que $E^{\circ}\left(\text{Cu}^{2+}/\text{Cu}\right)=+0{,}34$ V — a mesma diferença que faz a pilha de Daniell funcionar.`,
  },
  {
    topico: T,
    subtopico: "Reagente limitante",
    dificuldade: "dificil",
    enunciado: R`Misturam-se $28$ g de $\text{N}_2$ e $3{,}0$ g de $\text{H}_2$, que reagem formando amônia. Determine a massa máxima de $\text{NH}_3$ obtida. Massas molares: $\text{N}=14$, $\text{H}=1$ g/mol.`,
    correta: R`$17$ g`,
    distratores: [R`$34$ g`, R`$8{,}5$ g`, R`$28$ g`, R`$23$ g`],
    resolucao: R`As quantidades são $\dfrac{28}{28}=1{,}0$ mol de $\text{N}_2$ e $\dfrac{3{,}0}{2{,}0}=1{,}5$ mol de $\text{H}_2$. A equação $\text{N}_2+3\text{H}_2\rightarrow 2\text{NH}_3$ exigiria $3{,}0$ mol de hidrogênio para consumir todo o nitrogênio, e só há metade disso: o hidrogênio é o reagente limitante. Ele produz $\dfrac{2}{3}\times 1{,}5=1{,}0$ mol de amônia, isto é, $17$ g. Partir do nitrogênio, sem testar o limitante, levaria ao valor impossível de $34$ g.`,
  },
  {
    topico: T,
    subtopico: "Rendimento percentual",
    dificuldade: "dificil",
    enunciado: R`A partir de $0{,}50$ mol de $\text{N}_2$ e hidrogênio em excesso obtêm-se $13{,}6$ g de amônia. Determine o rendimento da reação, sabendo que $M(\text{NH}_3)=17$ g/mol.`,
    correta: R`$80{,}0\%$`,
    distratores: [R`$64{,}0\%$`, R`$40{,}0\%$`, R`$85{,}0\%$`, R`$75{,}0\%$`],
    resolucao: R`Pela estequiometria $\text{N}_2+3\text{H}_2\rightarrow 2\text{NH}_3$, meio mol de nitrogênio produziria $1{,}0$ mol de amônia, ou $17$ g — esse é o rendimento teórico. O rendimento percentual é a razão entre o obtido e o teórico: $\dfrac{13{,}6}{17}=0{,}800$, isto é, $80{,}0\%$. Rendimentos abaixo de $100\%$ são a regra, seja por reações paralelas, por perdas na separação ou, como no caso da síntese da amônia, por o sistema atingir o equilíbrio antes da conversão total.`,
  },
  {
    topico: T,
    subtopico: "Grau de pureza de amostra",
    dificuldade: "dificil",
    enunciado: R`A calcinação de $25{,}0$ g de um calcário produz $8{,}80$ g de $\text{CO}_2$. Determine a pureza da amostra em $\text{CaCO}_3$, sabendo que $M(\text{CaCO}_3)=100$ g/mol e $M(\text{CO}_2)=44$ g/mol.`,
    correta: R`$80{,}0\%$`,
    distratores: [R`$64{,}0\%$`, R`$88{,}0\%$`, R`$35{,}2\%$`, R`$75{,}0\%$`],
    resolucao: R`A reação é $\text{CaCO}_3\rightarrow\text{CaO}+\text{CO}_2$, na proporção de $1:1$. A quantidade de gás liberado é $\dfrac{8{,}80}{44}=0{,}200$ mol, que provém de $0{,}200$ mol de carbonato, ou $0{,}200\times 100=20{,}0$ g. A pureza é $\dfrac{20{,}0}{25{,}0}=0{,}800$, isto é, $80{,}0\%$; os $5{,}0$ g restantes são impurezas que não liberam gás. Note que o cálculo parte do produto medido, e não da massa total pesada.`,
  },
  {
    topico: T,
    subtopico: "Fórmula mínima a partir da composição percentual",
    dificuldade: "medio",
    enunciado: R`Um composto contém, em massa, $40{,}0\%$ de carbono, $6{,}7\%$ de hidrogênio e $53{,}3\%$ de oxigênio. Determine sua fórmula mínima.`,
    correta: R`$\text{CH}_2\text{O}$`,
    distratores: [
      R`$\text{C}_2\text{H}_4\text{O}_2$`,
      R`$\text{CHO}$`,
      R`$\text{C}_6\text{H}_{12}\text{O}_6$`,
      R`$\text{CH}_3\text{O}$`,
    ],
    resolucao: R`Tome $100$ g de amostra e converta em mols: $\dfrac{40{,}0}{12}=3{,}33$; $\dfrac{6{,}7}{1}=6{,}7$; $\dfrac{53{,}3}{16}=3{,}33$. Dividindo todos pelo menor, obtém-se $1:2:1$, logo $\text{CH}_2\text{O}$. As outras alternativas com essa mesma proporção — $\text{C}_2\text{H}_4\text{O}_2$ e $\text{C}_6\text{H}_{12}\text{O}_6$ — são fórmulas moleculares possíveis, mas a mínima é, por definição, a de menores índices inteiros.`,
  },
  {
    topico: T,
    subtopico: "Fórmula molecular a partir da fórmula mínima",
    dificuldade: "medio",
    enunciado: R`Um composto de fórmula mínima $\text{CH}_2\text{O}$ tem massa molar $180$ g/mol. Determine sua fórmula molecular.`,
    correta: R`$\text{C}_6\text{H}_{12}\text{O}_6$`,
    distratores: [
      R`$\text{C}_3\text{H}_6\text{O}_3$`,
      R`$\text{C}_5\text{H}_{10}\text{O}_5$`,
      R`$\text{C}_{12}\text{H}_{24}\text{O}_{12}$`,
      R`$\text{C}_4\text{H}_8\text{O}_4$`,
    ],
    resolucao: R`A massa da unidade mínima é $12+2(1)+16=30$ g/mol. O fator de multiplicação é $\dfrac{180}{30}=6$, de modo que a fórmula molecular é $\text{C}_6\text{H}_{12}\text{O}_6$ — a da glicose e de outras hexoses. Composição percentual sozinha nunca distingue esses isômeros e homólogos; é preciso conhecer a massa molar, obtida por espectrometria de massas ou por propriedades coligativas.`,
  },
  {
    topico: T,
    subtopico: "Análise elementar por combustão",
    dificuldade: "dificil",
    enunciado: R`A combustão completa de $0{,}255$ g de um composto de $\text{C}$, $\text{H}$ e $\text{O}$ produz $0{,}561$ g de $\text{CO}_2$ e $0{,}306$ g de $\text{H}_2\text{O}$. Determine a fórmula mínima do composto.`,
    correta: R`$\text{C}_3\text{H}_8\text{O}$`,
    distratores: [
      R`$\text{C}_3\text{H}_6\text{O}$`,
      R`$\text{C}_2\text{H}_6\text{O}$`,
      R`$\text{C}_3\text{H}_8\text{O}_2$`,
      R`$\text{CH}_4\text{O}$`,
    ],
    resolucao: R`Todo o carbono da amostra está no $\text{CO}_2$: $\dfrac{0{,}561}{44}=0{,}01275$ mol, ou $0{,}153$ g. Todo o hidrogênio está na água: $\dfrac{0{,}306}{18}=0{,}0170$ mol de $\text{H}_2\text{O}$, logo $0{,}0340$ mol de $\text{H}$, ou $0{,}034$ g. O oxigênio é obtido por diferença: $0{,}255-0{,}153-0{,}034=0{,}068$ g, isto é, $0{,}00425$ mol. Dividindo os três pelo menor: $3:8:1$, ou seja, $\text{C}_3\text{H}_8\text{O}$ — o propanol. O oxigênio jamais pode ser calculado a partir dos produtos, pois parte dele vem do ar.`,
  },
  {
    topico: T,
    subtopico: "Preparo de solução por diluição",
    dificuldade: "medio",
    enunciado: R`Determine o volume de solução de $\text{HCl}$ $2{,}00$ mol/L necessário para preparar $500$ mL de solução $0{,}100$ mol/L.`,
    correta: R`$25{,}0$ mL`,
    distratores: [R`$50{,}0$ mL`, R`$10{,}0$ mL`, R`$100{,}0$ mL`, R`$12{,}5$ mL`],
    resolucao: R`Na diluição a quantidade de soluto não muda, de modo que $C_1V_1=C_2V_2$. Então $V_1=\dfrac{0{,}100\times 500}{2{,}00}=25{,}0$ mL. Na prática, mede-se esse volume com pipeta, transfere-se para balão volumétrico de $500$ mL e completa-se com água até a marca — e, tratando-se de ácido concentrado, sempre se adiciona o ácido sobre a água, nunca o inverso.`,
  },
  {
    topico: T,
    subtopico: "Concentração de íons em mistura de soluções",
    dificuldade: "dificil",
    enunciado: R`Misturam-se $100$ mL de $\text{NaCl}$ $0{,}10$ mol/L com $100$ mL de $\text{CaCl}_2$ $0{,}10$ mol/L. Determine a concentração de íons cloreto na mistura.`,
    correta: R`$0{,}15$ mol/L`,
    distratores: [R`$0{,}30$ mol/L`, R`$0{,}10$ mol/L`, R`$0{,}20$ mol/L`, R`$0{,}075$ mol/L`],
    resolucao: R`Do $\text{NaCl}$ vêm $0{,}100\times 0{,}10=0{,}010$ mol de $\text{Cl}^{-}$. Do $\text{CaCl}_2$ vêm $0{,}100\times 0{,}10\times 2=0{,}020$ mol, pois cada fórmula libera dois cloretos. O total é $0{,}030$ mol num volume final de $0{,}200$ L, o que dá $0{,}15$ mol/L. Os dois erros típicos são esquecer o fator $2$ do cloreto de cálcio e esquecer a diluição provocada pela soma dos volumes.`,
  },
  {
    topico: T,
    subtopico: "Estequiometria com volume de gás",
    dificuldade: "dificil",
    enunciado: R`Determine o volume de $\text{CO}_2$ liberado, a $27\ ^{\circ}\text{C}$ e $1{,}0$ atm, na decomposição total de $10{,}0$ g de $\text{CaCO}_3$. Use $M=100$ g/mol e $R=0{,}0821$ atm·L/(mol·K).`,
    correta: R`$2{,}46$ L`,
    distratores: [R`$2{,}24$ L`, R`$4{,}92$ L`, R`$1{,}23$ L`, R`$24{,}6$ L`],
    resolucao: R`A decomposição $\text{CaCO}_3\rightarrow\text{CaO}+\text{CO}_2$ converte $\dfrac{10{,}0}{100}=0{,}100$ mol de carbonato em $0{,}100$ mol de gás. Pela equação dos gases ideais, $V=\dfrac{nRT}{P}=\dfrac{0{,}100\times 0{,}0821\times 300}{1{,}0}=2{,}46$ L. Usar $22{,}4$ L/mol daria $2{,}24$ L, resposta válida apenas nas CNTP — a temperatura aqui é $300$ K, e não $273$ K.`,
  },
  {
    topico: T,
    subtopico: "Pressões parciais e lei de Dalton",
    dificuldade: "dificil",
    enunciado: R`Um recipiente rígido de $10{,}0$ L a $300$ K contém $0{,}20$ mol de hélio e $0{,}30$ mol de neônio. Determine a pressão parcial do hélio, usando $R=0{,}0821$ atm·L/(mol·K).`,
    correta: R`$0{,}49$ atm`,
    distratores: [R`$1{,}23$ atm`, R`$0{,}74$ atm`, R`$0{,}25$ atm`, R`$2{,}46$ atm`],
    resolucao: R`A pressão parcial de um componente é a que ele exerceria sozinho no mesmo volume e temperatura: $p_{\text{He}}=\dfrac{n_{\text{He}}RT}{V}=\dfrac{0{,}20\times 0{,}0821\times 300}{10{,}0}\approx 0{,}49$ atm. A pressão total, $1{,}23$ atm, é a soma das parciais, conforme a lei de Dalton — consequência direta de as moléculas de um gás ideal não interagirem entre si, de modo que cada uma contribui independentemente.`,
  },
  {
    topico: T,
    subtopico: "Lei de efusão de Graham",
    dificuldade: "dificil",
    enunciado: R`Determine quantas vezes o hélio ($M=4{,}0$ g/mol) efunde mais rapidamente que o metano ($M=16{,}0$ g/mol) por um mesmo orifício, nas mesmas condições.`,
    correta: R`$2{,}0$`,
    distratores: [R`$4{,}0$`, R`$1{,}4$`, R`$0{,}5$`, R`$16{,}0$`],
    resolucao: R`A lei de Graham estabelece $\dfrac{v_1}{v_2}=\sqrt{\dfrac{M_2}{M_1}}$. Aqui, $\sqrt{\dfrac{16{,}0}{4{,}0}}=\sqrt{4}=2{,}0$. A raiz quadrada aparece porque, à mesma temperatura, todas as moléculas têm a mesma energia cinética média $\tfrac12 mv^{2}$: massas quatro vezes menores implicam velocidades apenas duas vezes maiores. Responder $4{,}0$ equivale a usar a razão direta das massas molares.`,
  },
  {
    topico: T,
    subtopico: "Massa molar a partir da densidade de um gás",
    dificuldade: "dificil",
    enunciado: R`Um gás tem densidade $1{,}96$ g/L nas CNTP. Determine sua massa molar, usando volume molar de $22{,}4$ L/mol.`,
    correta: R`$43{,}9$ g/mol`,
    distratores: [R`$21{,}9$ g/mol`, R`$28{,}0$ g/mol`, R`$64{,}0$ g/mol`, R`$87{,}8$ g/mol`],
    resolucao: R`A densidade é massa por volume, e um mol ocupa $22{,}4$ L nas CNTP: $M=d\cdot V_m=1{,}96\times 22{,}4\approx 43{,}9$ g/mol. O valor identifica o gás como dióxido de carbono ($44$ g/mol). A relação equivalente $M=\dfrac{dRT}{P}$ vale em quaisquer condições e é o fundamento do método de Dumas para determinar massas molares de líquidos voláteis.`,
  },
  {
    topico: T,
    subtopico: "Desvios do comportamento de gás ideal",
    dificuldade: "medio",
    enunciado: R`Em que condições um gás real mais se afasta do comportamento previsto pela equação dos gases ideais?`,
    correta: R`alta pressão e baixa temperatura`,
    distratores: [
      R`baixa pressão e alta temperatura`,
      R`alta pressão e alta temperatura`,
      R`baixa pressão e baixa temperatura`,
      R`quaisquer condições, igualmente`,
    ],
    resolucao: R`O modelo ideal supõe volume molecular desprezível e ausência de forças intermoleculares. Sob alta pressão as moléculas ficam próximas e seu volume próprio deixa de ser irrelevante; sob baixa temperatura a energia cinética cai e as forças atrativas passam a reter as moléculas, reduzindo a pressão exercida nas paredes. São exatamente os dois termos corrigidos na equação de van der Waals — e é por isso que todo gás se liquefaz quando comprimido e resfriado o bastante.`,
  },
  {
    topico: T,
    subtopico: "Volume de gás em reação de metal com ácido",
    dificuldade: "dificil",
    enunciado: R`Determine o volume de $\text{H}_2$ obtido nas CNTP ao se dissolver $1{,}30$ g de zinco em ácido clorídrico em excesso. Use $M(\text{Zn})=65{,}0$ g/mol e volume molar de $22{,}4$ L/mol.`,
    correta: R`$0{,}448$ L`,
    distratores: [R`$0{,}224$ L`, R`$0{,}896$ L`, R`$1{,}120$ L`, R`$4{,}480$ L`],
    resolucao: R`A quantidade de zinco é $\dfrac{1{,}30}{65{,}0}=0{,}0200$ mol. A reação $\text{Zn}+2\text{HCl}\rightarrow\text{ZnCl}_2+\text{H}_2$ libera um mol de gás por mol de metal, logo $0{,}0200$ mol de $\text{H}_2$. O volume é $0{,}0200\times 22{,}4=0{,}448$ L. Como o ácido está em excesso, o zinco é o reagente limitante e nenhum cálculo adicional sobre o $\text{HCl}$ é necessário.`,
  },
  {
    topico: T,
    subtopico: "Decomposição térmica e massa residual",
    dificuldade: "dificil",
    enunciado: R`Aquecendo-se $8{,}4$ g de bicarbonato de sódio, ocorre $2\text{NaHCO}_3\rightarrow\text{Na}_2\text{CO}_3+\text{H}_2\text{O}+\text{CO}_2$. Determine a massa do resíduo sólido, com $M(\text{NaHCO}_3)=84$ e $M(\text{Na}_2\text{CO}_3)=106$ g/mol.`,
    correta: R`$5{,}3$ g`,
    distratores: [R`$3{,}1$ g`, R`$8{,}4$ g`, R`$6{,}2$ g`, R`$4{,}2$ g`],
    resolucao: R`A amostra corresponde a $\dfrac{8{,}4}{84}=0{,}100$ mol de bicarbonato. Pela equação, dois mols produzem um de carbonato, de modo que se formam $0{,}0500$ mol, ou $0{,}0500\times 106=5{,}3$ g. A diferença de $3{,}1$ g escapa como vapor de água e gás carbônico — é essa liberação de $\text{CO}_2$ dentro da massa que faz o bicarbonato atuar como fermento químico.`,
  },
  {
    topico: T,
    subtopico: "Estequiometria industrial com rendimento",
    dificuldade: "dificil",
    enunciado: R`Numa planta de amônia, $28$ kg de $\text{N}_2$ reagem com hidrogênio em excesso com rendimento de $60\%$. Determine a massa de $\text{NH}_3$ obtida, com $M(\text{N}_2)=28$ e $M(\text{NH}_3)=17$ g/mol.`,
    correta: R`$20{,}4$ kg`,
    distratores: [R`$34{,}0$ kg`, R`$10{,}2$ kg`, R`$28{,}0$ kg`, R`$17{,}0$ kg`],
    resolucao: R`A massa dada corresponde a $1{,}0$ kmol de $\text{N}_2$, que pela equação $\text{N}_2+3\text{H}_2\rightarrow 2\text{NH}_3$ produziria $2{,}0$ kmol de amônia, ou $34{,}0$ kg — o rendimento teórico. Aplicando o rendimento real, $34{,}0\times 0{,}60=20{,}4$ kg. A proporção estequiométrica em quilomols é idêntica à em mols, o que dispensa converter as massas para gramas.`,
  },
  {
    topico: T,
    subtopico: "Análise gravimétrica de cloreto",
    dificuldade: "dificil",
    enunciado: R`Uma amostra de $1{,}000$ g contendo cloreto é tratada com excesso de $\text{AgNO}_3$, produzindo $1{,}435$ g de $\text{AgCl}$. Determine a porcentagem de cloro na amostra, com $M(\text{AgCl})=143{,}5$ e $M(\text{Cl})=35{,}5$ g/mol.`,
    correta: R`$35{,}5\%$`,
    distratores: [R`$14{,}4\%$`, R`$71{,}0\%$`, R`$25{,}0\%$`, R`$10{,}0\%$`],
    resolucao: R`O precipitado corresponde a $\dfrac{1{,}435}{143{,}5}=0{,}01000$ mol de $\text{AgCl}$, e cada fórmula contém um cloro: $0{,}01000$ mol, ou $0{,}01000\times 35{,}5=0{,}355$ g. Na amostra de $1{,}000$ g isso equivale a $35{,}5\%$. A gravimetria é confiável justamente por medir massa de um sólido insolúvel e de composição bem definida, sem depender de padronização de solução alguma.`,
  },
  {
    topico: T,
    subtopico: "Combustão completa e incompleta",
    dificuldade: "medio",
    enunciado: R`Um aquecedor a gás mal regulado, com entrada de ar insuficiente, produz chama amarelada e deposita fuligem. Além do carbono sólido, o produto perigoso formado nessas condições é:`,
    correta: R`$\text{CO}$`,
    distratores: [R`$\text{CO}_2$`, R`$\text{O}_3$`, R`$\text{NO}_2$`, R`$\text{H}_2\text{O}$`],
    resolucao: R`Com oxigênio suficiente, a combustão de um hidrocarboneto gera apenas $\text{CO}_2$ e $\text{H}_2\text{O}$. Faltando oxigênio, o carbono não se oxida por completo e aparecem monóxido de carbono e carbono elementar — a fuligem que escurece panelas. O $\text{CO}$ é inodoro e liga-se à hemoglobina com afinidade cerca de $200$ vezes maior que a do oxigênio, o que explica os envenenamentos por aquecedores em ambientes fechados.`,
  },
  {
    topico: T,
    subtopico: "Força e solubilidade de bases",
    dificuldade: "dificil",
    enunciado: R`O hidróxido de cálcio é classificado como base forte, embora sua solubilidade em água seja baixa. A conciliação entre os dois fatos está em que:`,
    correta: R`a fração dissolvida está totalmente dissociada`,
    distratores: [
      R`a fração dissolvida permanece na forma molecular`,
      R`a força de uma base independe de sua dissociação`,
      R`o sólido não dissolvido também libera hidróxido`,
      R`a base se converte em óxido ao dissolver`,
    ],
    resolucao: R`Força e solubilidade são propriedades distintas. Solubilidade mede quanto do sólido passa à solução; força mede o grau de dissociação daquilo que efetivamente se dissolveu. No $\text{Ca(OH)}_2$ a quantidade dissolvida é pequena, mas está $100\%$ na forma de $\text{Ca}^{2+}$ e $\text{OH}^{-}$ — daí ser base forte e, ao mesmo tempo, uma suspensão leitosa quando em excesso. O caso oposto é a amônia: infinitamente solúvel, porém base fraca.`,
  },
  {
    topico: T,
    subtopico: "Nomenclatura de sais ácidos",
    dificuldade: "medio",
    enunciado: R`Qual é o nome oficial do composto $\text{NaHCO}_3$?`,
    correta: R`hidrogenocarbonato de sódio`,
    distratores: [
      R`carbonato de sódio`,
      R`hidróxido de sódio carbonatado`,
      R`hidrogenocarbonato de sódio (II)`,
      R`carbeto de sódio hidratado`,
    ],
    resolucao: R`Sais ácidos conservam hidrogênios ionizáveis do ácido de origem, e a nomenclatura oficial os indica com o prefixo "hidrogeno-": $\text{NaHCO}_3$ é o hidrogenocarbonato de sódio, popularmente bicarbonato. O carbonato de sódio é o $\text{Na}_2\text{CO}_3$, sem hidrogênio. Como o sódio tem número de oxidação fixo $+1$, não se usa algarismo romano em seu nome.`,
  },
  {
    topico: T,
    subtopico: "Conversão entre título e concentração em quantidade de matéria",
    dificuldade: "dificil",
    enunciado: R`Uma solução comercial de $\text{H}_2\text{SO}_4$ tem $98\%$ em massa e densidade $1{,}84$ g/mL. Determine sua concentração em mol/L, com $M=98$ g/mol.`,
    correta: R`$18{,}4$ mol/L`,
    distratores: [R`$9{,}2$ mol/L`, R`$1{,}84$ mol/L`, R`$36{,}8$ mol/L`, R`$10{,}0$ mol/L`],
    resolucao: R`Tome $1{,}00$ L da solução: sua massa é $1000\times 1{,}84=1840$ g, dos quais $98\%$, ou $1803$ g, são ácido puro. Isso equivale a $\dfrac{1803}{98}=18{,}4$ mol. Como o volume tomado foi exatamente um litro, a concentração é $18{,}4$ mol/L. A forma compacta da conta é $C=\dfrac{1000\,d\,\tau}{M}$, relação que vale para qualquer solução concentrada.`,
  },
  {
    topico: T,
    subtopico: "Corrosão em metais revestidos",
    dificuldade: "dificil",
    enunciado: R`Uma chapa de ferro revestida de zinco e outra revestida de estanho são riscadas até expor o ferro. No ponto arranhado, a corrosão do ferro será:`,
    correta: R`acelerada apenas na chapa revestida de estanho`,
    distratores: [
      R`acelerada apenas na chapa revestida de zinco`,
      R`acelerada nas duas chapas igualmente`,
      R`impedida nas duas chapas igualmente`,
      R`impedida apenas na chapa revestida de estanho`,
    ],
    resolucao: R`O que decide é o potencial relativo. O zinco ($-0{,}76$ V) oxida-se mais facilmente que o ferro ($-0{,}44$ V) e continua a protegê-lo mesmo com o revestimento rompido, funcionando como ânodo de sacrifício. O estanho ($-0{,}14$ V) é menos reativo que o ferro: ao expor o metal, forma-se uma pilha em que o ferro é o ânodo e corrói mais depressa do que corroeria sozinho. É por isso que latas de folha-de-flandres amassadas enferrujam rapidamente.`,
  },
  {
    topico: T,
    subtopico: "Hidrácidos: substância pura e solução aquosa",
    dificuldade: "medio",
    enunciado: R`O composto $\text{HCl}$ recebe nomes diferentes conforme o estado em que se encontra. Qual é o nome correto do gás puro?`,
    correta: R`cloreto de hidrogênio`,
    distratores: [
      R`ácido clorídrico`,
      R`ácido hipocloroso`,
      R`hidreto de cloro`,
      R`cloro hidrogenado`,
    ],
    resolucao: R`No estado gasoso o $\text{HCl}$ é uma substância molecular covalente, sem íons, e recebe o nome de cloreto de hidrogênio. Só ao ser dissolvido em água ele se ioniza, produzindo $\text{H}_3\text{O}^{+}$ e $\text{Cl}^{-}$, e a solução resultante é o ácido clorídrico. A distinção não é mero formalismo: o gás seco não conduz corrente nem reage com metais, comportamentos que aparecem apenas na solução.`,
  },
];
