// Lote 3 de Química Geral — Tópico 2: Ligações Químicas.
// Estilo Brown, "Química: A Ciência Central" (caps. 8, 9, 11 e 12): Lewis,
// carga formal, ressonância, VSEPR, TLV/TOM, sólidos e forças intermoleculares.
// Sem questões `facil`.
const R = String.raw;
const T = "Ligações Químicas";

export const questoes = [
  {
    topico: T,
    subtopico: "Contagem de elétrons de valência em íon poliatômico",
    dificuldade: "medio",
    enunciado: R`Determine o número total de elétrons de valência que devem aparecer na estrutura de Lewis do íon clorato, $\text{ClO}_3^{-}$.`,
    correta: R`$26$`,
    distratores: [R`$24$`, R`$25$`, R`$32$`, R`$20$`],
    resolucao: R`O cloro pertence ao grupo $17$ e contribui com $7$ elétrons; cada oxigênio, do grupo $16$, contribui com $6$, totalizando $7+18=25$. A carga $1-$ acrescenta um elétron, resultando $26$. Esse total é o que deve ser distribuído entre ligações e pares isolados: três ligações simples consomem $6$ elétrons e os $20$ restantes completam o octeto dos três oxigênios e deixam um par isolado no cloro. Esquecer a carga do íon é o erro que leva a $25$.`,
  },
  {
    topico: T,
    subtopico: "Carga formal e escolha da estrutura de Lewis",
    dificuldade: "dificil",
    enunciado: R`Na estrutura de Lewis do íon sulfato, $\text{SO}_4^{2-}$, desenhada apenas com quatro ligações simples $\text{S}-\text{O}$, determine a carga formal do átomo de enxofre.`,
    correta: R`$+2$`,
    distratores: [R`$0$`, R`$-2$`, R`$+6$`, R`$+1$`],
    resolucao: R`A carga formal é $\text{CF}=n_{\text{val}}-n_{\text{isolados}}-\tfrac{1}{2}n_{\text{ligantes}}$. O enxofre tem $6$ elétrons de valência, nenhum par isolado nessa estrutura e oito elétrons em ligações: $\text{CF}=6-0-4=+2$. Cada oxigênio fica com $6-6-1=-1$, e a soma $+2+4(-1)=-2$ reproduz a carga do íon, como deve ser. É justamente essa distribuição desfavorável que motiva as estruturas alternativas com ligações duplas, nas quais a carga formal do enxofre cai a zero.`,
  },
  {
    topico: T,
    subtopico: "Ressonância e ordem de ligação fracionária",
    dificuldade: "dificil",
    enunciado: R`O íon nitrato, $\text{NO}_3^{-}$, é descrito por três estruturas de ressonância equivalentes, cada uma com uma ligação dupla e duas simples. Determine a ordem média da ligação $\text{N}-\text{O}$.`,
    correta: R`$1{,}33$`,
    distratores: [R`$1{,}00$`, R`$1{,}50$`, R`$2{,}00$`, R`$0{,}67$`],
    resolucao: R`Somando as três estruturas, cada posição $\text{N}-\text{O}$ aparece como dupla em uma delas e como simples nas outras duas, de modo que a ordem média é $\dfrac{2+1+1}{3}=\dfrac{4}{3}\approx 1{,}33$. A previsão é confirmada experimentalmente: as três distâncias $\text{N}-\text{O}$ são idênticas e intermediárias entre a de uma simples e a de uma dupla. O híbrido de ressonância é uma única espécie, e não uma mistura que oscila entre as três estruturas.`,
  },
  {
    topico: T,
    subtopico: "Exceções à regra do octeto",
    dificuldade: "medio",
    enunciado: R`Em qual das espécies abaixo o átomo central possui menos de oito elétrons na camada de valência?`,
    correta: R`$\text{BF}_3$`,
    distratores: [R`$\text{PCl}_5$`, R`$\text{SF}_6$`, R`$\text{CH}_4$`, R`$\text{NH}_4^{+}$`],
    resolucao: R`O boro tem apenas três elétrons de valência e, ao formar três ligações com o flúor, fica com seis elétrons — um octeto incompleto. Esse déficit é a razão de o $\text{BF}_3$ ser um ácido de Lewis vigoroso, capaz de aceitar um par isolado. $\text{PCl}_5$ e $\text{SF}_6$ são exemplos opostos, de octeto expandido, e as duas últimas espécies satisfazem a regra exatamente.`,
  },
  {
    topico: T,
    subtopico: "Energia de rede e a lei de Coulomb",
    dificuldade: "dificil",
    enunciado: R`Entre os compostos iônicos $\text{NaF}$, $\text{NaCl}$, $\text{KCl}$, $\text{KBr}$ e $\text{MgO}$, qual apresenta a maior energia de rede em módulo?`,
    correta: R`$\text{MgO}$`,
    distratores: [R`$\text{NaF}$`, R`$\text{NaCl}$`, R`$\text{KCl}$`, R`$\text{KBr}$`],
    resolucao: R`A energia de rede varia como $\dfrac{Q_1Q_2}{d}$. Nos quatro primeiros compostos as cargas são $1+$ e $1-$, e as diferenças vêm apenas da distância interiônica. No $\text{MgO}$ as cargas são $2+$ e $2-$, o que quadruplica o numerador, e os íons ainda são pequenos, o que reduz $d$. O resultado é uma energia de rede em torno de $3800$ kJ/mol, contra $788$ kJ/mol do $\text{NaCl}$ — e é essa diferença que explica o ponto de fusão do $\text{MgO}$ acima de $2800\ ^{\circ}\text{C}$.`,
  },
  {
    topico: T,
    subtopico: "Ciclo de Born-Haber: afinidade eletrônica",
    dificuldade: "dificil",
    enunciado: R`Para o $\text{KCl}$ são dados, em kJ/mol: $\Delta H_f^{\circ}=-437$; sublimação do $\text{K}$, $+89$; primeira ionização do $\text{K}$, $+419$; dissociação do $\text{Cl}_2$, $+243$; energia de rede, $-717$. Determine a afinidade eletrônica do cloro.`,
    correta: R`$-349$ kJ/mol`,
    distratores: [R`$-437$ kJ/mol`, R`$-717$ kJ/mol`, R`$+349$ kJ/mol`, R`$-121$ kJ/mol`],
    resolucao: R`O ciclo de Born-Haber decompõe a formação do sólido em etapas cuja soma deve reproduzir $\Delta H_f^{\circ}$. Note que apenas meio mol de $\text{Cl}_2$ é consumido, de modo que entra $\tfrac{243}{2}=121{,}5$. Assim $-437=89+419+121{,}5+\text{AE}+(-717)$, ou seja, $-437=-87{,}5+\text{AE}$ e $\text{AE}=-349{,}5\approx-349$ kJ/mol. O sinal negativo indica processo exotérmico, coerente com a alta afinidade eletrônica dos halogênios; usar $243$ inteiro é o descuido mais comum.`,
  },
  {
    topico: T,
    subtopico: "Entalpia de reação por energias de ligação",
    dificuldade: "dificil",
    enunciado: R`Estime $\Delta H$ da reação $\text{H}_2(g)+\text{Cl}_2(g)\rightarrow 2\,\text{HCl}(g)$ usando as energias médias de ligação, em kJ/mol: $\text{H}-\text{H}=436$, $\text{Cl}-\text{Cl}=242$ e $\text{H}-\text{Cl}=431$.`,
    correta: R`$-184$ kJ`,
    distratores: [R`$+184$ kJ`, R`$-247$ kJ`, R`$-431$ kJ`, R`$-92$ kJ`],
    resolucao: R`Vale $\Delta H=\sum E_{\text{ligações rompidas}}-\sum E_{\text{ligações formadas}}$. Rompem-se uma $\text{H}-\text{H}$ e uma $\text{Cl}-\text{Cl}$: $436+242=678$ kJ. Formam-se duas $\text{H}-\text{Cl}$: $2\times 431=862$ kJ. Logo $\Delta H=678-862=-184$ kJ. O processo é exotérmico porque as ligações formadas são, no conjunto, mais fortes que as rompidas. Esquecer o coeficiente $2$ do produto leva a $-92$ kJ, que é o valor por mol de $\text{HCl}$.`,
  },
  {
    topico: T,
    subtopico: "Ordem de ligação e comprimento de ligação",
    dificuldade: "dificil",
    enunciado: R`Ordene em ordem crescente de comprimento a ligação nitrogênio-nitrogênio nas espécies $\text{N}_2$, $\text{N}_2\text{F}_2$ e $\text{N}_2\text{H}_4$.`,
    correta: R`$\text{N}_2<\text{N}_2\text{F}_2<\text{N}_2\text{H}_4$`,
    distratores: [
      R`$\text{N}_2\text{H}_4<\text{N}_2\text{F}_2<\text{N}_2$`,
      R`$\text{N}_2\text{F}_2<\text{N}_2<\text{N}_2\text{H}_4$`,
      R`$\text{N}_2<\text{N}_2\text{H}_4<\text{N}_2\text{F}_2$`,
      R`$\text{N}_2\text{H}_4<\text{N}_2<\text{N}_2\text{F}_2$`,
    ],
    resolucao: R`Escrevendo as estruturas de Lewis: no $\text{N}_2$ a ligação é tripla, no $\text{N}_2\text{F}_2$ é dupla (cada nitrogênio faz ainda uma ligação com flúor e guarda um par isolado) e no $\text{N}_2\text{H}_4$ é simples. Quanto maior a ordem de ligação, maior a densidade eletrônica entre os núcleos, mais forte a atração e menor a distância de equilíbrio. Os valores medidos confirmam: $110$ pm, $122$ pm e $147$ pm, respectivamente.`,
  },
  {
    topico: T,
    subtopico: "VSEPR com par isolado em bipirâmide trigonal",
    dificuldade: "dificil",
    enunciado: R`Determine a geometria molecular do $\text{SF}_4$, sabendo que o enxofre possui um par isolado além das quatro ligações.`,
    correta: R`gangorra`,
    distratores: [R`tetraédrica`, R`quadrado planar`, R`bipirâmide trigonal`, R`pirâmide quadrada`],
    resolucao: R`São cinco domínios eletrônicos em torno do enxofre, o que define arranjo de bipirâmide trigonal. O par isolado, mais volumoso, ocupa preferencialmente uma posição equatorial, onde sofre repulsão de apenas dois vizinhos a $90^{\circ}$ em vez de três. Restam dois flúores axiais e dois equatoriais, e o formato resultante lembra uma gangorra. A resposta "bipirâmide trigonal" descreve o arranjo dos domínios, não a geometria dos núcleos.`,
  },
  {
    topico: T,
    subtopico: "VSEPR com dois pares isolados",
    dificuldade: "dificil",
    enunciado: R`Determine a geometria molecular do $\text{ClF}_3$, molécula em que o cloro é o átomo central.`,
    correta: R`forma de T`,
    distratores: [R`trigonal plana`, R`pirâmide trigonal`, R`bipirâmide trigonal`, R`tetraédrica`],
    resolucao: R`O cloro tem $7$ elétrons de valência; três são usados nas ligações com os flúores e sobram dois pares isolados, totalizando cinco domínios — arranjo de bipirâmide trigonal. Os dois pares isolados ocupam posições equatoriais, que oferecem mais espaço, deixando os três flúores em um plano com dois deles axiais e um equatorial: o conjunto tem forma de T, com ângulos ligeiramente menores que $90^{\circ}$ pela repulsão extra dos pares isolados.`,
  },
  {
    topico: T,
    subtopico: "VSEPR com octeto expandido",
    dificuldade: "medio",
    enunciado: R`Determine a geometria molecular do $\text{XeF}_4$.`,
    correta: R`quadrado planar`,
    distratores: [R`tetraédrica`, R`gangorra`, R`pirâmide quadrada`, R`octaédrica`],
    resolucao: R`O xenônio traz $8$ elétrons de valência; quatro participam das ligações e os outros quatro formam dois pares isolados. São seis domínios, logo arranjo octaédrico. Os dois pares isolados se posicionam em vértices opostos, o mais longe possível um do outro, e os quatro flúores ficam no plano equatorial, com ângulos de exatamente $90^{\circ}$. A geometria molecular é, portanto, quadrado planar — e a molécula é apolar, apesar das quatro ligações polares.`,
  },
  {
    topico: T,
    subtopico: "VSEPR em íon poliatômico linear",
    dificuldade: "dificil",
    enunciado: R`Determine a geometria do íon triiodeto, $\text{I}_3^{-}$, no qual um átomo de iodo é central.`,
    correta: R`linear`,
    distratores: [R`angular`, R`forma de T`, R`trigonal plana`, R`piramidal`],
    resolucao: R`O iodo central tem $7$ elétrons de valência mais o elétron da carga negativa: $8$. Dois formam as ligações com os iodos terminais e os seis restantes constituem três pares isolados — cinco domínios, arranjo de bipirâmide trigonal. Os três pares isolados ocupam as três posições equatoriais, e os dois ligantes ficam nas axiais, a $180^{\circ}$ um do outro. A geometria molecular é linear, embora o arranjo eletrônico não seja.`,
  },
  {
    topico: T,
    subtopico: "Comparação de ângulos de ligação",
    dificuldade: "dificil",
    enunciado: R`Ordene em ordem decrescente os ângulos de ligação nas moléculas $\text{CH}_4$, $\text{NH}_3$ e $\text{H}_2\text{O}$.`,
    correta: R`$\text{CH}_4>\text{NH}_3>\text{H}_2\text{O}$`,
    distratores: [
      R`$\text{H}_2\text{O}>\text{NH}_3>\text{CH}_4$`,
      R`$\text{NH}_3>\text{CH}_4>\text{H}_2\text{O}$`,
      R`$\text{CH}_4>\text{H}_2\text{O}>\text{NH}_3$`,
      R`$\text{H}_2\text{O}>\text{CH}_4>\text{NH}_3$`,
    ],
    resolucao: R`As três moléculas têm quatro domínios eletrônicos e arranjo tetraédrico, mas diferem no número de pares isolados: zero, um e dois. Um par isolado é atraído por um único núcleo e ocupa uma região angularmente mais larga que um par ligante, comprimindo os ângulos restantes. Daí a sequência medida $109{,}5^{\circ}$, $107^{\circ}$ e $104{,}5^{\circ}$. A hierarquia geral de repulsão é par isolado-par isolado maior que par isolado-par ligante, maior que par ligante-par ligante.`,
  },
  {
    topico: T,
    subtopico: "Polaridade molecular e simetria",
    dificuldade: "medio",
    enunciado: R`Qual das moléculas abaixo é polar, apesar de todas possuírem ligações covalentes polares?`,
    correta: R`$\text{SO}_2$`,
    distratores: [R`$\text{CO}_2$`, R`$\text{BF}_3$`, R`$\text{CCl}_4$`, R`$\text{SF}_6$`],
    resolucao: R`A polaridade da molécula é a soma vetorial dos dipolos de ligação, e depende da geometria. $\text{CO}_2$ é linear, $\text{BF}_3$ trigonal plana, $\text{CCl}_4$ tetraédrica e $\text{SF}_6$ octaédrica: em todas elas os vetores se cancelam por simetria. Já o $\text{SO}_2$ é angular, por causa do par isolado no enxofre, e os dois dipolos $\text{S}-\text{O}$ têm resultante não nula. A consequência prática aparece na solubilidade: o $\text{SO}_2$ é muito solúvel em água, o $\text{CO}_2$ não.`,
  },
  {
    topico: T,
    subtopico: "Momento dipolar e caráter iônico percentual",
    dificuldade: "dificil",
    enunciado: R`A molécula de $\text{HCl}$ tem momento dipolar de $1{,}08$ D e comprimento de ligação de $127$ pm. Sabendo que uma separação de cargas inteiras a essa distância corresponderia a $6{,}10$ D, determine o caráter iônico percentual da ligação.`,
    correta: R`$17{,}7\%$`,
    distratores: [R`$45{,}0\%$`, R`$27{,}3\%$`, R`$9{,}0\%$`, R`$82{,}3\%$`],
    resolucao: R`O caráter iônico percentual é a razão entre o momento dipolar observado e aquele que a molécula teria se o elétron fosse transferido por inteiro: $\dfrac{1{,}08}{6{,}10}=0{,}177$, isto é, $17{,}7\%$. O resultado quantifica algo que a eletronegatividade só indica qualitativamente: a ligação $\text{H}-\text{Cl}$ é predominantemente covalente, com uma carga parcial de cerca de $0{,}18$ unidade sobre cada átomo, e não um par iônico.`,
  },
  {
    topico: T,
    subtopico: "Contagem de ligações sigma e pi",
    dificuldade: "dificil",
    enunciado: R`Determine o número de ligações $\sigma$ e $\pi$ na molécula de propino, $\text{CH}_3-\text{C}\equiv\text{CH}$.`,
    correta: R`$6\ \sigma$ e $2\ \pi$`,
    distratores: [R`$4\ \sigma$ e $2\ \pi$`, R`$6\ \sigma$ e $1\ \pi$`, R`$8\ \sigma$ e $0\ \pi$`, R`$5\ \sigma$ e $3\ \pi$`],
    resolucao: R`Toda ligação simples é uma $\sigma$; uma tripla é composta por uma $\sigma$ e duas $\pi$. Contando: três ligações $\text{C}-\text{H}$ da metila, uma $\text{C}-\text{C}$ simples, a componente $\sigma$ da tripla e a ligação $\text{C}-\text{H}$ terminal somam seis $\sigma$; as duas componentes restantes da tripla são as $\pi$. As ligações $\pi$ resultam da superposição lateral de orbitais $p$ não hibridizados e são mais fracas que a $\sigma$, o que explica a reatividade dos alcinos.`,
  },
  {
    topico: T,
    subtopico: "Hibridização com octeto expandido",
    dificuldade: "dificil",
    enunciado: R`Determine a hibridização do átomo central na molécula de $\text{XeF}_2$.`,
    correta: R`$sp^{3}d$`,
    distratores: [R`$sp^{3}$`, R`$sp^{2}$`, R`$sp^{3}d^{2}$`, R`$sp$`],
    resolucao: R`O xenônio possui oito elétrons de valência: dois participam das ligações com os flúores e seis formam três pares isolados. O número de domínios eletrônicos é cinco, e o modelo de ligação de valência descreve esse arranjo misturando um orbital $s$, três $p$ e um $d$, o que gera cinco orbitais híbridos $sp^{3}d$ dirigidos aos vértices de uma bipirâmide trigonal. A geometria molecular observada é linear, porque três dos cinco híbridos abrigam pares isolados.`,
  },
  {
    topico: T,
    subtopico: "Hibridização em íon com ressonância",
    dificuldade: "medio",
    enunciado: R`Determine a hibridização do átomo de carbono no íon carbonato, $\text{CO}_3^{2-}$.`,
    correta: R`$sp^{2}$`,
    distratores: [R`$sp^{3}$`, R`$sp$`, R`$sp^{3}d$`, R`$sp^{3}d^{2}$`],
    resolucao: R`O carbono está ligado a três oxigênios e não possui pares isolados: são três domínios eletrônicos, arranjo trigonal plano e hibridização $sp^{2}$. O orbital $p$ remanescente, perpendicular ao plano, superpõe-se aos orbitais $p$ dos três oxigênios formando um sistema $\pi$ deslocalizado — a tradução, em linguagem de orbitais, das três estruturas de ressonância equivalentes do íon.`,
  },
  {
    topico: T,
    subtopico: "TOM: ordem de ligação na série do oxigênio",
    dificuldade: "dificil",
    enunciado: R`Usando a teoria do orbital molecular, ordene em ordem crescente de comprimento de ligação as espécies $\text{O}_2$, $\text{O}_2^{-}$ e $\text{O}_2^{2-}$.`,
    correta: R`$\text{O}_2<\text{O}_2^{-}<\text{O}_2^{2-}$`,
    distratores: [
      R`$\text{O}_2^{2-}<\text{O}_2^{-}<\text{O}_2$`,
      R`$\text{O}_2^{-}<\text{O}_2<\text{O}_2^{2-}$`,
      R`$\text{O}_2<\text{O}_2^{2-}<\text{O}_2^{-}$`,
      R`$\text{O}_2^{2-}<\text{O}_2<\text{O}_2^{-}$`,
    ],
    resolucao: R`Os elétrons acrescentados entram nos orbitais antiligantes $\pi^{*}_{2p}$, que já estavam parcialmente ocupados no $\text{O}_2$. A ordem de ligação, $\tfrac{1}{2}\left(n_{\text{lig}}-n_{\text{antilig}}\right)$, cai de $2$ para $1{,}5$ e depois para $1$. Menor ordem significa ligação mais fraca e mais longa: $121$ pm, $133$ pm e $149$ pm. É por isso que o íon superóxido e o peróxido são espécies reativas, enquanto o $\text{O}_2$ é comparativamente estável.`,
  },
  {
    topico: T,
    subtopico: "TOM: paramagnetismo do oxigênio",
    dificuldade: "dificil",
    enunciado: R`O oxigênio líquido é atraído por um ímã, comportamento que a estrutura de Lewis usual do $\text{O}_2$ não prevê. A teoria do orbital molecular explica o fato porque nela:`,
    correta: R`dois elétrons ocupam $\pi^{*}$ desemparelhados`,
    distratores: [
      R`os elétrons dos orbitais $\pi^{*}$ estão emparelhados`,
      R`a ordem de ligação resultante é igual a um`,
      R`os orbitais $\pi^{*}$ permanecem inteiramente vazios`,
      R`existe uma ligação dupla localizada entre os átomos`,
    ],
    resolucao: R`Preenchendo os orbitais moleculares do $\text{O}_2$, os dois últimos elétrons vão para os orbitais degenerados $\pi^{*}_{2p}$ e, pela regra de Hund, ocupam-nos separadamente com spins paralelos. A molécula é, portanto, um birradical, e o momento magnético resultante explica a atração pelo ímã. A ordem de ligação continua sendo $2$, compatível com a dupla da estrutura de Lewis — que, no entanto, mostra todos os elétrons emparelhados e erra na previsão magnética.`,
  },
  {
    topico: T,
    subtopico: "TOM: existência de espécies com ordem fracionária",
    dificuldade: "dificil",
    enunciado: R`Determine a ordem de ligação do íon $\text{He}_2^{+}$, que é detectado experimentalmente, ao contrário da molécula $\text{He}_2$.`,
    correta: R`$0{,}5$`,
    distratores: [R`$0{,}0$`, R`$1{,}0$`, R`$1{,}5$`, R`$2{,}0$`],
    resolucao: R`O íon tem três elétrons: dois preenchem o orbital ligante $\sigma_{1s}$ e o terceiro ocupa o antiligante $\sigma^{*}_{1s}$. A ordem de ligação vale $\tfrac{1}{2}(2-1)=0{,}5$, positiva, o que basta para manter os núcleos unidos, ainda que de modo fraco. No $\text{He}_2$ neutro haveria dois elétrons em cada orbital, ordem zero e nenhuma estabilização — motivo pelo qual o hélio é monoatômico.`,
  },
  {
    topico: T,
    subtopico: "TOM: efeito da ionização sobre a ligação",
    dificuldade: "dificil",
    enunciado: R`Ao remover um elétron do $\text{N}_2$ formando $\text{N}_2^{+}$, a ligação enfraquece; ao remover um elétron do $\text{O}_2$ formando $\text{O}_2^{+}$, ela se fortalece. A razão dessa diferença é que o elétron removido sai:`,
    correta: R`de orbital ligante no $\text{N}_2$ e antiligante no $\text{O}_2$`,
    distratores: [
      R`de orbital antiligante nas duas moléculas`,
      R`de orbital ligante nas duas moléculas`,
      R`de orbital não ligante no $\text{N}_2$`,
      R`de orbital $\sigma$ no $\text{O}_2$ e $\pi$ no $\text{N}_2$`,
    ],
    resolucao: R`No $\text{N}_2$ o orbital ocupado de maior energia é o ligante $\sigma_{2p}$; retirar dele um elétron derruba a ordem de ligação de $3$ para $2{,}5$, alongando e enfraquecendo a ligação. No $\text{O}_2$ o orbital ocupado de maior energia é o antiligante $\pi^{*}_{2p}$; retirar um elétron dali eleva a ordem de $2$ para $2{,}5$, encurtando a ligação de $121$ pm para $112$ pm. O caso mostra que ionizar nem sempre desestabiliza a ligação.`,
  },
  {
    topico: T,
    subtopico: "Ligação pi e isomeria geométrica",
    dificuldade: "dificil",
    enunciado: R`O 1,2-dicloroeteno existe nas formas cis e trans, que não se interconvertem à temperatura ambiente, enquanto o 1,2-dicloroetano não apresenta isômeros desse tipo. A razão é que a ligação $\pi$:`,
    correta: R`impede a rotação em torno do eixo internuclear`,
    distratores: [
      R`é mais forte que a ligação $\sigma$ correspondente`,
      R`torna a molécula obrigatoriamente polar`,
      R`aumenta o comprimento da ligação entre os carbonos`,
      R`localiza os elétrons sobre o eixo internuclear`,
    ],
    resolucao: R`A ligação $\pi$ nasce da superposição lateral de dois orbitais $p$ paralelos. Girar um carbono em relação ao outro desalinharia esses orbitais e destruiria a superposição, o que custa cerca de $270$ kJ/mol — barreira alta demais para ser vencida por agitação térmica ordinária. Na ligação simples só há a $\sigma$, cuja densidade eletrônica é cilíndrica em torno do eixo, e a rotação é praticamente livre.`,
  },
  {
    topico: T,
    subtopico: "Energia de ressonância do benzeno",
    dificuldade: "dificil",
    enunciado: R`A hidrogenação do ciclo-hexeno libera $120$ kJ/mol, mas a hidrogenação completa do benzeno libera apenas $208$ kJ/mol. Determine a energia de ressonância do benzeno.`,
    correta: R`$152$ kJ/mol`,
    distratores: [R`$88$ kJ/mol`, R`$328$ kJ/mol`, R`$120$ kJ/mol`, R`$208$ kJ/mol`],
    resolucao: R`Se o benzeno fosse apenas um cicloexatrieno com três ligações duplas isoladas, sua hidrogenação liberaria $3\times 120=360$ kJ/mol. O valor medido é $208$ kJ/mol, ou seja, $360-208=152$ kJ/mol a menos. Essa diferença mede o quanto o benzeno real é mais estável que a estrutura hipotética de ligações localizadas, estabilização que vem da deslocalização dos seis elétrons $\pi$ por todo o anel.`,
  },
  {
    topico: T,
    subtopico: "Anomalia de ponto de ebulição nos haletos de hidrogênio",
    dificuldade: "dificil",
    enunciado: R`Na série $\text{HCl}$, $\text{HBr}$ e $\text{HI}$ o ponto de ebulição cresce com a massa molar, mas o $\text{HF}$, o mais leve de todos, ferve acima de todos eles. O motivo é:`,
    correta: R`a ligação de hidrogênio entre as moléculas de $\text{HF}$`,
    distratores: [
      R`a maior massa molar efetiva do $\text{HF}$`,
      R`a maior polarizabilidade do flúor`,
      R`a menor energia da ligação $\text{H}-\text{F}$`,
      R`o caráter iônico total da ligação no $\text{HF}$`,
    ],
    resolucao: R`De $\text{HCl}$ a $\text{HI}$ o número de elétrons cresce, a polarizabilidade aumenta e as forças de dispersão de London tornam-se progressivamente mais intensas, elevando o ponto de ebulição. O $\text{HF}$ foge da série porque o flúor, pequeno e muito eletronegativo, permite ligações de hidrogênio genuínas entre moléculas vizinhas, muito mais fortes que a dispersão. O mesmo salto aparece na comparação entre $\text{H}_2\text{O}$ e $\text{H}_2\text{S}$ e entre $\text{NH}_3$ e $\text{PH}_3$.`,
  },
  {
    topico: T,
    subtopico: "Forças de dispersão e forma molecular",
    dificuldade: "dificil",
    enunciado: R`O $n$-pentano ferve a $36\ ^{\circ}\text{C}$ e o neopentano, seu isômero, a $10\ ^{\circ}\text{C}$, embora ambos tenham fórmula $\text{C}_5\text{H}_{12}$. A explicação está em que a molécula linear:`,
    correta: R`tem maior área de contato entre as moléculas`,
    distratores: [
      R`possui momento dipolar permanente`,
      R`forma ligações de hidrogênio intermoleculares`,
      R`tem massa molar ligeiramente maior`,
      R`apresenta ligações covalentes mais fortes`,
    ],
    resolucao: R`Os dois isômeros têm o mesmo número de elétrons e, portanto, polarizabilidade total semelhante, mas as forças de dispersão dependem também de quanto as superfícies moleculares conseguem se aproximar. A cadeia linear do $n$-pentano permite contato ao longo de todo o comprimento, enquanto o neopentano, quase esférico e compacto, só se toca em pequenas regiões. Ambos são apolares e não fazem ligação de hidrogênio, o que elimina as demais explicações.`,
  },
  {
    topico: T,
    subtopico: "Estrutura do gelo e ligações de hidrogênio",
    dificuldade: "medio",
    enunciado: R`Diferentemente da maioria das substâncias, a água tem o sólido menos denso que o líquido. A causa é que, no gelo:`,
    correta: R`cada molécula faz quatro ligações de hidrogênio direcionais`,
    distratores: [
      R`as moléculas ficam mais distantes por repulsão eletrostática`,
      R`as ligações covalentes $\text{O}-\text{H}$ se alongam`,
      R`o número de moléculas por mol diminui`,
      R`as forças de dispersão superam as ligações de hidrogênio`,
    ],
    resolucao: R`No gelo cada molécula doa dois hidrogênios e aceita dois pares isolados, ligando-se a quatro vizinhas em geometria aproximadamente tetraédrica. Esse arranjo direcional gera uma rede hexagonal cheia de vazios e, portanto, pouco compacta. Ao fundir, parte das ligações se rompe, as moléculas colapsam nesses espaços e a densidade aumenta até o máximo em $4\ ^{\circ}\text{C}$. É por isso que o gelo flutua e os lagos congelam de cima para baixo.`,
  },
  {
    topico: T,
    subtopico: "Viscosidade e número de grupos hidroxila",
    dificuldade: "medio",
    enunciado: R`A viscosidade a $25\ ^{\circ}\text{C}$ cresce na sequência etanol, etilenoglicol, glicerol, substâncias de massas molares próximas. A explicação é o aumento:`,
    correta: R`do número de grupos hidroxila por molécula`,
    distratores: [
      R`da polarizabilidade das cadeias carbônicas`,
      R`do comprimento da cadeia carbônica`,
      R`da massa molar das substâncias`,
      R`da pressão de vapor de cada líquido`,
    ],
    resolucao: R`Etanol, etilenoglicol e glicerol têm um, dois e três grupos hidroxila, respectivamente. Cada $\text{OH}$ adicional multiplica os pontos de ancoragem para ligações de hidrogênio entre moléculas vizinhas, aumentando a resistência ao escoamento. O efeito é grande: a viscosidade do glicerol é cerca de mil vezes a do etanol. Pelo mesmo motivo cresce a tensão superficial e cai a pressão de vapor ao longo da série.`,
  },
  {
    topico: T,
    subtopico: "Pressão de vapor e forças intermoleculares",
    dificuldade: "dificil",
    enunciado: R`Entre as substâncias $\text{CH}_3\text{OCH}_3$, $\text{CH}_3\text{CH}_2\text{OH}$, $\text{H}_2\text{O}$, $\text{CH}_3\text{CH}_2\text{CH}_2\text{OH}$ e $\text{C}_3\text{H}_5(\text{OH})_3$, qual apresenta a maior pressão de vapor a $25\ ^{\circ}\text{C}$?`,
    correta: R`$\text{CH}_3\text{OCH}_3$`,
    distratores: [
      R`$\text{CH}_3\text{CH}_2\text{OH}$`,
      R`$\text{H}_2\text{O}$`,
      R`$\text{CH}_3\text{CH}_2\text{CH}_2\text{OH}$`,
      R`$\text{C}_3\text{H}_5(\text{OH})_3$`,
    ],
    resolucao: R`A pressão de vapor mede a facilidade de escapar do líquido e é tanto maior quanto mais fracas forem as forças intermoleculares. O éter dimetílico é isômero do etanol, mas não possui hidrogênio ligado a oxigênio: suas moléculas interagem apenas por dipolo-dipolo e dispersão, sem ligações de hidrogênio. Todas as demais substâncias da lista têm pelo menos um grupo $\text{OH}$, e o glicerol, com três, é a menos volátil. O éter dimetílico é, de fato, gasoso à temperatura ambiente.`,
  },
  {
    topico: T,
    subtopico: "Classificação de sólidos por propriedades",
    dificuldade: "dificil",
    enunciado: R`Uma substância funde a $801\ ^{\circ}\text{C}$, é quebradiça, não conduz corrente no estado sólido, mas conduz bem quando fundida ou dissolvida em água. Classifique esse sólido.`,
    correta: R`iônico`,
    distratores: [R`metálico`, R`molecular`, R`covalente reticular`, R`amorfo`],
    resolucao: R`O alto ponto de fusão indica forças de coesão intensas, o que já elimina os sólidos moleculares. A ausência de condução no estado sólido descarta o metálico, em que os elétrons são móveis em qualquer estado. O critério decisivo é a condução após a fusão: significa que existem portadores de carga que estavam presos na rede e passam a se mover — íons. Um sólido covalente reticular como o quartzo não conduz nem fundido, pois seus elétrons permanecem localizados nas ligações.`,
  },
  {
    topico: T,
    subtopico: "Cela unitária cúbica de faces centradas",
    dificuldade: "dificil",
    enunciado: R`Determine o número de átomos por cela unitária numa estrutura cúbica de faces centradas.`,
    correta: R`$4$`,
    distratores: [R`$2$`, R`$1$`, R`$6$`, R`$8$`],
    resolucao: R`Cada um dos oito átomos dos vértices é compartilhado por oito celas vizinhas e contribui com $\tfrac18$: são $8\times\tfrac18=1$ átomo. Cada um dos seis átomos centrados nas faces é dividido entre duas celas e contribui com $\tfrac12$: são $6\times\tfrac12=3$. O total é $1+3=4$ átomos por cela. Para comparação, a cúbica de corpo centrado contém $2$ e a cúbica simples, $1$ — e é dessa contagem que se extrai a densidade do metal.`,
  },
  {
    topico: T,
    subtopico: "Densidade a partir da cela unitária",
    dificuldade: "dificil",
    enunciado: R`O ferro cristaliza no sistema cúbico de corpo centrado com aresta $a=287$ pm. Calcule sua densidade, usando $M=55{,}85$ g/mol e $N_A=6{,}022\times 10^{23}$ mol$^{-1}$.`,
    correta: R`$7{,}85$ g/cm³`,
    distratores: [R`$3{,}92$ g/cm³`, R`$15{,}7$ g/cm³`, R`$5{,}24$ g/cm³`, R`$11{,}8$ g/cm³`],
    resolucao: R`A cela de corpo centrado contém $8\times\tfrac18+1=2$ átomos. A massa da cela é $\dfrac{2\times 55{,}85}{6{,}022\times 10^{23}}=1{,}855\times 10^{-22}$ g. O volume é $a^{3}=\left(2{,}87\times 10^{-8}\ \text{cm}\right)^{3}=2{,}364\times 10^{-23}$ cm³. Dividindo, $\rho=\dfrac{1{,}855\times 10^{-22}}{2{,}364\times 10^{-23}}\approx 7{,}85$ g/cm³, em ótimo acordo com o valor experimental. Usar um átomo por cela conduziria à metade do valor.`,
  },
  {
    topico: T,
    subtopico: "Ligação covalente coordenada",
    dificuldade: "medio",
    enunciado: R`Ao misturar $\text{NH}_3$ e $\text{BF}_3$ forma-se o aduto $\text{H}_3\text{N}-\text{BF}_3$. A ligação que une os dois fragmentos é:`,
    correta: R`covalente coordenada, com o par vindo do nitrogênio`,
    distratores: [
      R`covalente coordenada, com o par vindo do boro`,
      R`iônica, por transferência de elétron do boro`,
      R`de hidrogênio, entre o $\text{NH}_3$ e o flúor`,
      R`metálica, por deslocalização dos elétrons`,
    ],
    resolucao: R`O nitrogênio da amônia tem um par isolado disponível e atua como base de Lewis; o boro do trifluoreto tem apenas seis elétrons de valência, um orbital $p$ vazio, e atua como ácido de Lewis. Os dois elétrons da nova ligação são fornecidos integralmente pelo nitrogênio — daí o nome ligação coordenada, embora, depois de formada, ela seja indistinguível de qualquer outra covalente. A geometria em torno do boro muda de trigonal plana para tetraédrica.`,
  },
  {
    topico: T,
    subtopico: "Número de estruturas de ressonância equivalentes",
    dificuldade: "medio",
    enunciado: R`Determine o número de estruturas de ressonância equivalentes que descrevem a molécula de $\text{SO}_3$, escritas com uma ligação dupla e duas simples.`,
    correta: R`$3$`,
    distratores: [R`$2$`, R`$4$`, R`$6$`, R`$1$`],
    resolucao: R`A ligação dupla pode estar em qualquer um dos três oxigênios, e as três alternativas são equivalentes por simetria: são três estruturas de ressonância. O híbrido resultante tem as três ligações idênticas, com ordem média $\tfrac{2+1+1}{3}\approx 1{,}33$, e a molécula é trigonal plana e apolar. O mesmo raciocínio se aplica ao $\text{NO}_3^{-}$; já o $\text{NO}_2^{-}$, angular, admite apenas duas.`,
  },
  {
    topico: T,
    subtopico: "Polaridade em geometrias de cinco e seis domínios",
    dificuldade: "dificil",
    enunciado: R`Entre as moléculas $\text{PF}_5$, $\text{SF}_4$, $\text{XeF}_4$, $\text{CF}_4$ e $\text{SF}_6$, qual é polar?`,
    correta: R`$\text{SF}_4$`,
    distratores: [R`$\text{PF}_5$`, R`$\text{XeF}_4$`, R`$\text{CF}_4$`, R`$\text{SF}_6$`],
    resolucao: R`Todas têm ligações polares, e o que decide é a simetria. $\text{PF}_5$ (bipirâmide trigonal), $\text{CF}_4$ (tetraédrica) e $\text{SF}_6$ (octaédrica) distribuem os ligantes simetricamente e anulam os dipolos; no $\text{XeF}_4$ os dois pares isolados ficam em vértices opostos do octaedro e o arranjo quadrado planar dos flúores também se cancela. No $\text{SF}_4$, porém, o único par isolado equatorial quebra a simetria da bipirâmide e a resultante é não nula.`,
  },
  {
    topico: T,
    subtopico: "Momento dipolar: efeito do par isolado",
    dificuldade: "dificil",
    enunciado: R`A amônia tem momento dipolar de $1{,}47$ D, enquanto o $\text{NF}_3$, de geometria idêntica, tem apenas $0{,}24$ D, embora a ligação $\text{N}-\text{F}$ seja mais polar que a $\text{N}-\text{H}$. A causa é que, no $\text{NF}_3$:`,
    correta: R`os dipolos de ligação opõem-se ao do par isolado`,
    distratores: [
      R`a geometria é trigonal plana e simétrica`,
      R`o nitrogênio perde seu par isolado`,
      R`as ligações $\text{N}-\text{F}$ são praticamente apolares`,
      R`o flúor é menos eletronegativo que o hidrogênio`,
    ],
    resolucao: R`As duas moléculas são pirâmides trigonais, com um par isolado no nitrogênio que contribui com um dipolo apontando para fora, no eixo. Na amônia o nitrogênio é o extremo negativo das ligações, e o dipolo das ligações aponta no mesmo sentido do par isolado: as contribuições se somam. No $\text{NF}_3$ o flúor é mais eletronegativo que o nitrogênio, os dipolos de ligação apontam para os flúores, em sentido oposto ao do par isolado, e o cancelamento quase completo deixa um momento resultante pequeno.`,
  },
  {
    topico: T,
    subtopico: "Energia de ligação e inércia química do nitrogênio",
    dificuldade: "dificil",
    enunciado: R`O $\text{N}_2$ constitui $78\%$ da atmosfera e é praticamente inerte à temperatura ambiente, apesar de a formação da amônia a partir dele ser exotérmica. A explicação para essa inércia é:`,
    correta: R`a altíssima energia da ligação tripla nitrogênio-nitrogênio`,
    distratores: [
      R`a entalpia positiva da formação da amônia`,
      R`a baixa concentração de hidrogênio na atmosfera`,
      R`a apolaridade da molécula de nitrogênio`,
      R`a entropia desfavorável da reação direta`,
    ],
    resolucao: R`Romper a tripla do $\text{N}_2$ custa $941$ kJ/mol, uma das maiores energias de ligação conhecidas, o que impõe uma barreira de ativação enorme a qualquer reação. Trata-se de um impedimento cinético, não termodinâmico: a síntese da amônia tem $\Delta H^{\circ}=-92$ kJ/mol e é espontânea em condições apropriadas. A indústria contorna a barreira com catalisador de ferro, alta pressão e temperatura da ordem de $450\ ^{\circ}\text{C}$ — o processo Haber-Bosch.`,
  },
  {
    topico: T,
    subtopico: "Interações íon-dipolo na dissolução",
    dificuldade: "medio",
    enunciado: R`A dissolução do $\text{NaCl}$ em água exige vencer uma energia de rede de $788$ kJ/mol, e ainda assim ocorre facilmente. A interação responsável por compensar esse custo é:`,
    correta: R`força íon-dipolo`,
    distratores: [R`força dipolo-dipolo`, R`dispersão de London`, R`ligação de hidrogênio`, R`ligação covalente dativa`],
    resolucao: R`As moléculas de água orientam o extremo negativo do seu dipolo, o oxigênio, ao redor dos cátions $\text{Na}^{+}$ e os hidrogênios parcialmente positivos ao redor dos ânions $\text{Cl}^{-}$. Essa interação íon-dipolo é a mais forte entre as intermoleculares e libera uma energia de hidratação de magnitude comparável à da rede, deixando um saldo entálpico pequeno que a variação de entropia positiva completa. Ligações de hidrogênio ocorrem entre as próprias moléculas de água, não entre elas e os íons.`,
  },
  {
    topico: T,
    subtopico: "Teoria de bandas: condutividade e temperatura",
    dificuldade: "dificil",
    enunciado: R`Ao se aquecer uma amostra, a condutividade elétrica de um metal diminui, mas a de um semicondutor aumenta. A explicação, segundo a teoria de bandas, é que no semicondutor:`,
    correta: R`elétrons são promovidos através do intervalo de energia`,
    distratores: [
      R`as vibrações da rede deixam de espalhar os portadores`,
      R`o intervalo entre as bandas aumenta com a temperatura`,
      R`a banda de valência se esvazia completamente`,
      R`a mobilidade dos elétrons cresce com o aquecimento`,
    ],
    resolucao: R`No metal a banda está parcialmente preenchida e o número de portadores já é máximo; aquecer só intensifica as vibrações da rede, que espalham os elétrons e aumentam a resistividade. No semicondutor a banda de valência está cheia e a de condução, vazia, separadas por um intervalo pequeno (cerca de $1{,}1$ eV no silício). A energia térmica promove elétrons através desse intervalo, criando pares elétron-lacuna: o número de portadores cresce exponencialmente e domina sobre o espalhamento.`,
  },
  {
    topico: T,
    subtopico: "Ligas substitucionais e intersticiais",
    dificuldade: "medio",
    enunciado: R`O aço-carbono comum, com até cerca de $2\%$ de carbono dissolvido no ferro, é classificado como liga:`,
    correta: R`intersticial`,
    distratores: [R`substitucional`, R`heterogênea`, R`intermetálica`, R`eutética simples`],
    resolucao: R`Numa liga substitucional os átomos do soluto ocupam posições da rede antes pertencentes ao solvente, o que exige raios atômicos semelhantes — é o caso do latão, em que o zinco substitui átomos de cobre. O carbono tem raio muito menor que o do ferro e se aloja nos interstícios entre os átomos da rede, travando o deslizamento dos planos cristalinos. Esse travamento é exatamente o que torna o aço muito mais duro e resistente que o ferro puro.`,
  },
  {
    topico: T,
    subtopico: "Carga formal e número de oxidação",
    dificuldade: "dificil",
    enunciado: R`Na molécula de $\text{CO}_2$, o número de oxidação do carbono é $+4$, mas sua carga formal é zero. A diferença entre os dois conceitos está em que o número de oxidação:`,
    correta: R`atribui os elétrons ao átomo mais eletronegativo`,
    distratores: [
      R`divide os elétrons igualmente entre os átomos ligados`,
      R`considera apenas os pares isolados de cada átomo`,
      R`é calculado a partir da geometria molecular`,
      R`equivale à carga real medida sobre o átomo`,
    ],
    resolucao: R`A carga formal supõe partilha igualitária dos elétrons de ligação: o carbono, com quatro elétrons de valência e oito elétrons ligantes, fica com $4-\tfrac{8}{2}=0$. O número de oxidação faz a hipótese extrema oposta, entregando os elétrons de cada ligação por inteiro ao átomo mais eletronegativo: o carbono perde todos os oito e fica $+4$. Nenhum dos dois é a carga real, que é intermediária — são convenções de contabilidade úteis para fins diferentes.`,
  },
];
